"""Topic data for Module 05 Sets, Logic & Proof."""
from __future__ import annotations

# Helper to build concept dicts compactly
def C(title, body, callout, ct, cb, q, steps, answer):
    return {
        "title": title,
        "body": body if isinstance(body, list) else [body],
        "callout": callout,
        "callout_title": ct,
        "callout_body": cb if isinstance(cb, list) else [cb],
        "q": q,
        "steps": steps,
        "answer": answer,
    }


TOPICS: list[dict] = []

# ═══════════════════════════════════════════════════════════════════════════════
# 5.1 SET THEORY BASICS
# ═══════════════════════════════════════════════════════════════════════════════
TOPICS.append({
    "id": "5.1",
    "title": "Set Theory Basics",
    "tags": "#maths/sets #maths/logic #cs/data-structures #cs/types",
    "prereq": ["4.10 Geometry for Computer Graphics"],
    "used_later": ["5.2 Subsets Unions and Intersections", "5.5 Propositional Logic"],
    "next": "5.2 Subsets Unions and Intersections",
    "plain": "A **set** is a well-defined collection of distinct objects. Set theory gives you precise language for grouping items, testing membership, and describing collections without ambiguity.\n\nBefore logic and proof, you need a way to talk about \"all the items that satisfy a rule.\" That is exactly what sets do. In computer science, sets appear as hash sets, database result rows, permission groups, and type membership.",
    "everyday": "Your music playlist is a set of songs. Each song is an element. You can ask \"is this song in my playlist?\" — that is a membership test.",
    "terms": [
        ("set", "a well-defined collection of distinct objects, with no duplicates and no order."),
        ("element", "an individual object that belongs to a set."),
        ("membership", "the relationship between an element and a set, written a ∈ A when a belongs to A."),
        ("empty set", "the set with no elements, written ∅ or {}."),
        ("universal set", "the set containing every object under discussion in a particular context, often written U."),
    ],
    "concepts": [
        C("What Is a Set?",
           ["A [[set]] groups objects that share a rule or belong to a named collection.",
            "",
            "Two common ways to describe a set:",
            "",
            "**Roster notation** — list the elements inside braces:",
            "",
            "```text",
            "A = {2, 4, 6, 8}",
            "```",
            "",
            "**Set-builder notation** — describe the rule:",
            "",
            "```text",
            "B = {x | x is an even positive integer less than 10}",
            "```",
            "",
            "Both describe the same set: {2, 4, 6, 8}.",
            "",
            "Key properties:",
            "- **No duplicates**: {1, 1, 2} = {1, 2}",
            "- **No order**: {3, 1, 2} = {1, 2, 3}",
            "- **Well-defined**: every object either belongs or does not belong — no ambiguity."],
           "important", "Well-defined means no guesswork",
           ["\"Nice numbers\" is not a set — people disagree on membership.",
            "\"Prime numbers less than 20\" is a set — the rule is precise."],
           "Write the set of first five positive odd integers using roster notation.",
           ["List odd positive integers starting from 1.",
            "Stop after five elements: 1, 3, 5, 7, 9.",
            "Write in braces: {1, 3, 5, 7, 9}."],
           "**{1, 3, 5, 7, 9}**"),
        C("Elements and Membership",
           ["An [[element]] is one member of a set. [[membership]] tells you whether an object belongs.",
            "",
            "Symbols:",
            "",
            "```text",
            "a ∈ A   means a is an element of A",
            "a ∉ A   means a is not an element of A",
            "```",
            "",
            "Example:",
            "",
            "```text",
            "V = {a, e, i, o, u}",
            "a ∈ V    ✓",
            "z ∉ V    ✓",
            "```",
            "",
            "In Python, `in` performs membership testing:",
            "",
            "```python",
            "vowels = {'a', 'e', 'i', 'o', 'u'}",
            "'a' in vowels   # True",
            "'z' in vowels   # False",
            "```",
            "",
            "This connects to [[1.1 Counting and Number Sense]] — counting elements is how you measure set size."],
           "tip", "Read ∈ as \"is in\"",
           ["When you see `3 ∈ {1, 2, 3}`, read it as \"3 is in the set {1, 2, 3}.\""],
           "Let S = {2, 4, 6, 8, 10}. Is 6 ∈ S? Is 7 ∈ S?",
           ["Check whether 6 appears in the roster: yes, 6 is listed.",
            "Check whether 7 appears: no, 7 is not listed.",
            "Write membership statements."],
           "**6 ∈ S** and **7 ∉ S**"),
        C("The Empty Set",
           ["The [[empty set]] contains no elements. It is written **∅** or **{}**.",
            "",
            "Examples of empty sets:",
            "",
            "```text",
            "E = {x | x is a prime number and x < 2}   →  ∅",
            "F = {x | x² = -1 and x is real}            →  ∅",
            "```",
            "",
            "> [!warning] ∅ is not \"nothing to think about\"",
            "> The empty set is a valid set. It appears constantly in CS: an empty list, zero search results, no permissions granted.",
            "",
            "Important distinction:",
            "",
            "```text",
            "∅        the empty set (no elements)",
            "{∅}      a set whose only element is the empty set (one element)",
            "```",
            "",
            "So |∅| = 0 but |{∅}| = 1. This distinction matters in recursive data structures."],
           "example", "Empty in CS",
           ["A database query returning zero rows gives an empty result set.",
            "An empty hash set in Python: `set()` or `set([])`."],
           "How many elements does ∅ have? How many does {∅} have?",
           ["∅ has no elements, so the count is 0.",
            "{∅} contains one element (the empty set itself), so the count is 1.",
            "These are different sets."],
           "**|∅| = 0** and **|{∅}| = 1**"),
        C("The Universal Set",
           ["The [[universal set]] **U** is the set of all objects under discussion in a given context.",
            "",
            "Example: when working with single letters, you might set:",
            "",
            "```text",
            "U = {a, b, c, ..., z}",
            "```",
            "",
            "Every set you discuss in that context is a subset of U.",
            "",
            "In a Venn diagram, U is the rectangle that contains all other sets (see [[5.3 Venn Diagrams and Cardinality]]).",
            "",
            "The universal set depends on context:",
            "",
            "```text",
            "Context: students in a class",
            "U = {all enrolled students}",
            "",
            "Context: integers",
            "U = {..., -2, -1, 0, 1, 2, ...}",
            "```",
            "",
            "There is no single universal set for all of mathematics — you choose U to fit the problem."],
           "important", "Context fixes U",
           ["In a permissions system, U might be all users.",
            "In a type system, U might be all values of a given type."],
           "In a class of 30 students, U is the set of all 30. A = {students who play chess}. Can A contain someone not in U?",
           ["By definition, every set under discussion is a subset of U.",
            "A student not in U is outside the problem context.",
            "So no — A cannot contain anyone outside U."],
           "**No.** Every element of A must be in U."),
        C("Roster vs Set-Builder Notation",
           ["**Roster notation** lists elements explicitly. Use it when the set is small.",
            "",
            "```text",
            "Days = {Mon, Tue, Wed, Thu, Fri, Sat, Sun}",
            "```",
            "",
            "**Set-builder notation** describes a rule. Use it when the set is large or infinite.",
            "",
            "```text",
            "Evens = {n | n ∈ ℤ, n is even}",
            "```",
            "",
            "Read the vertical bar as \"such that.\"",
            "",
            "Both notations can describe the same set:",
            "",
            "```text",
            "{1, 4, 9, 16} = {n² | n ∈ {1, 2, 3, 4}}",
            "```",
            "",
            "Set-builder notation connects to SQL `WHERE` clauses — you select elements satisfying a condition."],
           "tip", "Choose the clearer notation",
           ["For {1, 2, 3}, roster is clearer.",
            "For {n | n is prime and n < 1000}, set-builder is necessary."],
           "Write set-builder notation for {2, 4, 6, 8, 10}.",
           ["Identify the rule: even positive integers.",
            "Add the constraint: from 2 to 10.",
            "Write: {n | n is even, 2 ≤ n ≤ 10}."],
           "**{n | n is even, 2 ≤ n ≤ 10}** (or {2n | n ∈ {1, 2, 3, 4, 5}})"),
        C("Sets in Programming",
           ["Sets model unique collections in code:",
            "",
            "```python",
            "# Python set",
            "permissions = {'read', 'write', 'execute'}",
            "'read' in permissions        # membership",
            "len(permissions)             # cardinality (later topic)",
            "```",
            "",
            "```sql",
            "-- SQL returns a set of rows",
            "SELECT user_id FROM users WHERE active = true;",
            "```",
            "",
            "Type systems use set-like thinking:",
            "",
            "```text",
            "int ∈ Numeric types",
            "string ∈ Text types",
            "```",
            "",
            "Sets from [[4.10 Geometry for Computer Graphics]] appear as collections of vertices, edges, and faces — each is a set of points or indices."],
           "example", "Hash sets guarantee uniqueness",
           ["Inserting a duplicate into a Python set has no effect — the set stays the same.",
            "This mirrors the mathematical rule that {1, 1, 2} = {1, 2}."],
           "A program stores user IDs in a set. ID 42 is added twice. How many times does 42 appear?",
           ["Sets have no duplicates by definition.",
            "Adding 42 twice is the same as adding it once.",
            "42 appears exactly once."],
           "**Once.** Sets contain each element at most once."),
    ],
    "why": "Set theory works because it replaces vague words like \"some items\" with precise membership rules. Every element either belongs or does not belong — there is no third option. This binary membership is the foundation for Boolean logic in [[5.5 Propositional Logic]] and for database queries in [[5.2 Subsets Unions and Intersections]].\n\nThe empty set and universal set give you boundary cases that appear in every CS system: zero results, all possible values, and the question \"is this item in the collection?\"",
    "mistakes": [
        "Writing {1, 2, 2, 3} as if duplicates matter — they do not; the set is {1, 2, 3}.",
        "Confusing ∅ with {∅} — the first has 0 elements, the second has 1.",
        "Using roster notation for infinite sets — use set-builder instead.",
        "Forgetting that order does not matter: {a, b, c} = {c, a, b}.",
        "Treating \"nice numbers\" or \"big sets\" as valid sets — they are not well-defined.",
        "Writing 3 ⊂ {1, 2, 3} — 3 is an element, not a subset (use ∈ not ⊂).",
    ],
    "failure": "If you confuse ∈ (element of) with ⊆ (subset of), every later set operation will go wrong. Check: is the object a single item or a collection?",
    "cs_intro": "Sets appear wherever programs group unique items:",
    "cs_body": [
        "- **Hash sets** (`set` in Python, `HashSet` in Java) — fast membership testing",
        "- **Database results** — each query returns a set of rows",
        "- **Permission systems** — a user's roles form a set of capabilities",
        "- **Type systems** — a value belongs to a type (membership)",
        "- **Network allowlists** — a set of permitted IP addresses",
        "",
        "Example:",
        "",
        "```python",
        "allowed_ports = {80, 443, 8080}",
        "if request_port in allowed_ports:",
        "    accept()",
        "else:",
        "    reject()",
        "```",
    ],
    "checkpoint": [
        "What is a set, in one sentence?",
        "What does a ∈ A mean?",
        "What is the empty set?",
        "What is the universal set?",
        "How is roster notation different from set-builder notation?",
        "Is {1, 2, 3} = {3, 2, 1}? Why?",
        "How many elements does ∅ have?",
        "Give one CS example of a set.",
    ],
    "mini_quiz": [
        "Write the set of vowels in {a, b, c, d, e}.",
        "Is 5 ∈ {2, 4, 6, 8}?",
        "Write ∅ in roster notation.",
        "Explain why {1, 1, 2} = {1, 2}.",
        "Write set-builder notation for {3, 6, 9, 12}.",
        "How many elements does {∅} have?",
        "Name the two membership symbols and their meanings.",
        "Is \"large numbers\" a well-defined set? Why or why not?",
        "Write a Python-style membership test for checking if 'admin' is in a roles set.",
        "Explain one reason sets matter in computer science.",
    ],
    "pass_gate": [
        "write sets in roster and set-builder notation",
        "use ∈ and ∉ correctly",
        "distinguish ∅ from {∅}",
        "explain the universal set in context",
    ],
    "worked": [
        {"title": "Roster notation", "q": "Write the set of prime numbers less than 10.",
         "steps": ["List primes starting from 2.", "2, 3, 5, 7 are prime and less than 10.", "4, 6, 8, 9 are not prime.", "Write: {2, 3, 5, 7}."],
         "answer": "{2, 3, 5, 7}"},
        {"title": "Membership testing", "q": "A = {1, 3, 5, 7, 9}. Which of 2, 3, 6, 9 belong to A?",
         "steps": ["Check each number against the roster.", "2 ∉ A, 3 ∈ A, 6 ∉ A, 9 ∈ A.", "List members: 3 and 9."],
         "answer": "3 ∈ A and 9 ∈ A; 2 ∉ A and 6 ∉ A"},
        {"title": "Empty vs singleton-of-empty", "q": "Compare ∅ and {∅}.",
         "steps": ["∅ has no elements: |∅| = 0.", "{∅} has one element (the empty set): |{∅}| = 1.", "They are not equal sets."],
         "answer": "∅ has 0 elements; {∅} has 1 element"},
        {"title": "Set-builder notation", "q": "Write {1, 4, 9, 16, 25} in set-builder notation.",
         "steps": ["Recognise perfect squares.", "1=1², 4=2², ..., 25=5².", "Write {n² | n ∈ {1, 2, 3, 4, 5}}."],
         "answer": "{n² | n ∈ {1, 2, 3, 4, 5}}"},
        {"title": "Spot the mistake", "q": "A learner writes: \"3 ⊂ {1, 2, 3}.\" Fix the error.",
         "steps": ["3 is a single number, not a set.", "Single items use ∈ (element of), not ⊂ (subset of).", "Correct statement: 3 ∈ {1, 2, 3}."],
         "answer": "3 ∈ {1, 2, 3} (not ⊂)", "note": "∈ is for elements; ⊆ is for subsets (see 5.2)."},
        {"title": "CS application", "q": "A firewall allowlist is {22, 80, 443}. A request arrives on port 8080. What happens?",
         "steps": ["Test membership: 8080 ∈ {22, 80, 443}?", "8080 is not in the set.", "The request is rejected (not in allowlist)."],
         "answer": "Request rejected — 8080 ∉ allowlist"},
    ],
    "practice_sections": [
        ["Define [[set]] in your own words.", "Define [[element]].", "Define [[membership]].", "Define [[empty set]].", "Define [[universal set]].", "What does well-defined mean for a set?"],
        ["Write roster notation for the first six positive integers.", "Write {2, 4, 6, 8, 10} in set-builder notation.", "Let A = {a, e, i, o, u}. Is 'e' ∈ A?", "How many elements does ∅ have?", "How many elements does {∅, {1}} have?", "Is {1, 2, 3} = {3, 2, 1}? Justify.", "Write the set of prime numbers less than 15.", "Is 0 ∈ {1, 2, 3}?"],
        ["A learner writes {1, 1, 2, 3}. What is the correct set?", "A learner says |∅| = 1. Explain the error.", "A learner writes 5 ⊂ {3, 5, 7}. Fix it.", "A learner claims {x | x is big} is a set. Explain why not.", "A learner lists {Mon, Tue, Wed, Mon}. What is wrong?"],
        ["Write set-builder notation for multiples of 3 less than 20.", "If U = {1, ..., 10} and A = {2, 4, 6, 8, 10}, is every element of A in U?", "Compare ∅ and {∅}. Give |∅| and |{∅}|.", "Write the set of letters in the word 'MISSISSIPPI' (no duplicates).", "True or false: every set is a subset of itself. (Preview of 5.2 — explain your thinking.)"],
        ["Explain how Python's `in` operator relates to ∈.", "A database returns rows matching a filter. How is this like set-builder notation?", "Give an example of a universal set in a web application context.", "Why do hash sets ignore duplicate insertions?", "Write a one-line Python set containing three port numbers."],
    ],
    "practice_answers": [
        ["A set is a well-defined collection of distinct objects with no duplicates and no order.",
         "An element is an individual object belonging to a set.",
         "Membership is the relationship between an element and a set, written a ∈ A.",
         "The empty set ∅ contains no elements.",
         "The universal set U contains every object under discussion in a given context.",
         "Well-defined means any object either belongs or does not belong — no ambiguity."],
        ["{1, 2, 3, 4, 5, 6}.", "{n | n is even, 2 ≤ n ≤ 10}.", "Yes, 'e' ∈ A.", "0.", "2 (elements are ∅ and {1}).", "Yes — order does not matter.", "{2, 3, 5, 7, 11, 13}.", "No, 0 ∉ {1, 2, 3}."],
        ["{1, 2, 3} — duplicates are removed.", "|∅| = 0, not 1. ∅ has no elements.", "5 ∈ {3, 5, 7} (5 is an element, not a subset).", "'Big' is not well-defined — no precise rule.", "Duplicate Mon — sets have no duplicates; correct set is {Mon, Tue, Wed}."],
        ["{n | n = 3k, k ∈ ℕ, n < 20} = {3, 6, 9, 12, 15, 18}.", "Yes — A ⊆ U (all elements of A are in U).", "|∅| = 0, |{∅}| = 1.", "{M, I, S, P} (four distinct letters).", "True — every set is a subset of itself (formal proof in 5.2)."],
        ["`x in S` returns True iff x ∈ S mathematically.", "SELECT ... WHERE condition selects elements satisfying a rule, like {x | condition(x)}.", "U could be all registered users; subsets are active users, admins, etc.", "Sets by definition contain each element at most once.", "`ports = {80, 443, 8080}`"],
    ],
    "mastery_b": [
        "Write roster notation for the first five positive even integers.",
        "Write {1, 8, 27, 64} in set-builder notation.",
        "Let B = {2, 4, 6}. Is 4 ∈ B? Is 5 ∈ B?",
        "How many elements does {∅} have?",
        "Write the set of consonants in {a, b, c, d, e}.",
        "Explain why {1, 2, 2, 3} = {1, 2, 3}.",
    ],
    "mastery_c": [
        "A learner writes |∅| = 1. Explain and correct.",
        "A learner writes 7 ⊆ {5, 6, 7}. Fix the notation.",
    ],
    "mastery_d": [
        "Write set-builder notation for {5, 10, 15, 20, 25}.",
        "If U = {1, 2, ..., 20}, describe A = {prime numbers in U} in set-builder notation.",
        "Compare ∅ and {∅, ∅}. How many elements does each have?",
    ],
    "mastery_e": [
        "Explain how a Python `set` models a mathematical set.",
        "A permission check `if 'admin' in roles` — what set operation is this?",
        "Give one example of a universal set in a file-system context.",
        "Why is {∅} different from ∅ in a recursive data structure?",
        "Write one sentence explaining why sets belong in a CS maths course.",
    ],
    "mastery_answers": [
        "**set**: a well-defined collection of distinct objects. **element**: one member of a set. **membership**: the ∈ relationship. **empty set**: ∅, no elements. **universal set**: all objects under discussion.",
        "{2, 4, 6, 8, 10}.", "{n³ | n ∈ {1, 2, 3, 4}}.", "4 ∈ B; 5 ∉ B.", "1.", "{b, c, d}.", "Duplicates are ignored; order does not matter.",
        "|∅| = 0. ∅ has no elements.", "7 ∈ {5, 6, 7} (not ⊆).",
        "{5n | n ∈ {1, 2, 3, 4, 5}}.", "A = {n | n ∈ U, n is prime}.", "|∅| = 0; |{∅, ∅}| = 1 (one element, the empty set).",
        "Python sets store unique elements with no order, matching mathematical sets.", "Membership test (∈).", "U = all files in a directory; subsets are .txt files, hidden files, etc.", "{∅} contains one element (the empty set); ∅ contains none — different in tree structures.", "Sets model collections, permissions, and query results precisely.",
    ],
    "glossary_builds": {"set": "1.1 Counting and Number Sense", "element": "set", "membership": "set", "empty set": "set", "universal set": "set"},
    "glossary_cs": {
        "set": "Hash sets and database result rows are set-like collections with membership testing.",
        "element": "Each item in a Python set or each row in a query result is an element.",
        "membership": "The `in` operator in Python tests whether a value is an element of a collection.",
        "empty set": "An empty query result or `set()` in Python represents the empty set.",
        "universal set": "The domain of all possible values in a type system acts as a universal set.",
    },
    "cs_one_liner": "Sets model collections, database results, permissions, and types.",
    "plain_short": "Group objects and describe membership precisely.",
})
