"""Topic data for Module 10 CS Applications generator."""

TOPICS = []

# =============================================================================
# 10.1 Big O, Theta and Omega
# =============================================================================
TOPICS.append({
    "id": "10.1",
    "title": "Big O Theta and Omega",
    "tags": "#maths/discrete #cs/complexity #cs/algorithms",
    "prereq": ["9.10 Convex Optimisation Basics", "2.7 Inequalities", "3.2 Function Notation and Mapping"],
    "used_later": ["10.2 Algorithm Complexity Case Studies", "11.1 Advanced Complexity Theory"],
    "next": "10.2 Algorithm Complexity Case Studies",
    "plain": "**Asymptotic notation** classifies how an algorithm's cost grows as input size increases, ignoring constant factors and lower-order terms. [[Big O]] gives an upper bound (worst-case growth rate), [[Big Omega]] a lower bound, and [[Big Theta]] a tight bound when upper and lower match. This is the standard language for comparing sorting algorithms, search trees, and network protocols without running every benchmark.",
    "everyday": "If doubling your shopping list makes checkout take roughly twice as long, your checkout process grows linearly — like O(n). If doubling the list makes it four times slower, that smells quadratic — like O(n²).",
    "terms": [
        ("Big O", "notation f(n) = O(g(n)) meaning f grows no faster than a constant times g for large n."),
        ("Big Theta", "notation f(n) = Θ(g(n)) meaning f is bounded above and below by constant multiples of g."),
        ("Big Omega", "notation f(n) = Ω(g(n)) meaning f grows at least as fast as a constant times g for large n."),
        ("asymptotic growth", "behaviour of a function as n tends to infinity, ignoring constants."),
        ("dominant term", "the highest-order term in a cost expression that controls growth for large n."),
    ],
    "concepts": [
        concept(
            "What Asymptotic Notation Measures",
            [
                "When you analyse an algorithm, you count **operations** as a function of input size n.",
                "",
                "From [[1.1 Counting and Number Sense]] you already count steps carefully. Here the question becomes: **as n gets huge, which part of the formula dominates?**",
                "",
                "Example cost:",
                "",
                "```text",
                "T(n) = 3n² + 50n + 200",
                "```",
                "",
                "For n = 10, the constant 200 matters.",
                "For n = 1,000,000, the term 3n² dominates.",
                "",
                "Asymptotic notation keeps the [[dominant term]] and drops the rest.",
            ],
            "tip", "Think 'scaling', not 'exact count'",
            ["A loop that runs n times with 5 operations inside is still O(n), not O(5n). Constants are intentionally ignored."],
            "Identify the [[dominant term]] in T(n) = 7n log n + 100n + 500.",
            ["List each term: 7n log n, 100n, 500.", "Compare growth rates: log n < n < n log n < n².", "For large n, 7n log n grows fastest among these.", "Drop coefficients and lower-order terms."],
            "**Θ(n log n)** — the n log n term dominates.",
        ),
        concept(
            "Big O — Upper Bound",
            [
                "Write **f(n) = O(g(n))** when f is **eventually bounded above** by a constant times g.",
                "",
                "Formal idea (from [[2.7 Inequalities]]): there exist c > 0 and n₀ such that for all n ≥ n₀:",
                "",
                "```text",
                "f(n) ≤ c · g(n)",
                "```",
                "",
                "Plain English: f grows **no faster than** g, up to a constant factor.",
                "",
                "Example: 3n + 10 = O(n) because 3n + 10 ≤ 4n for n ≥ 10.",
            ],
            "important", "Big O is an upper bound, not an exact formula",
            ["Saying T(n) = O(n²) does not prove T(n) = n² exactly — it might be O(n). Always give the **tightest** reasonable upper bound."],
            "Prove that 2n + 5 = O(n).",
            ["Need c and n₀ with 2n + 5 ≤ cn for n ≥ n₀.", "Choose c = 3. Then 2n + 5 ≤ 3n when 5 ≤ n.", "So n₀ = 5 works.", "Therefore 2n + 5 = O(n)."],
            "**O(n)** with c = 3, n₀ = 5.",
        ),
        concept(
            "Big Omega — Lower Bound",
            [
                "**f(n) = Ω(g(n))** means f is **eventually bounded below** by a constant times g:",
                "",
                "```text",
                "f(n) ≥ c · g(n)   for n ≥ n₀",
                "```",
                "",
                "Every algorithm that must look at all n items at least once has cost Ω(n).",
                "",
                "This connects to **lower bounds** in [[5.9 Direct Proof and Counterexample]]: you prove no algorithm can beat a certain rate.",
            ],
            "example", "Sorting lower bound",
            ["Comparison-based sorting of n distinct items requires Ω(n log n) comparisons in the worst case — you cannot reliably sort faster without extra structure."],
            "A function must print every element of an array of length n. What is a valid Omega bound?",
            ["Printing each element takes at least one operation per element.", "So T(n) ≥ n for n ≥ 1.", "That matches Ω(n) with c = 1, n₀ = 1.", "It is not Ω(n²) unless extra work is forced."],
            "**Ω(n)** — you must touch each element at least once.",
        ),
        concept(
            "Big Theta — Tight Bound",
            [
                "**f(n) = Θ(g(n))** when f is both O(g) and Ω(g):",
                "",
                "```text",
                "c₁·g(n) ≤ f(n) ≤ c₂·g(n)",
                "```",
                "",
                "Θ means **same growth rate** — upper and lower bounds match up to constants.",
                "",
                "If a nested loop runs n × n times with O(1) body, T(n) = Θ(n²).",
            ],
            "warning", "Do not confuse O with Θ",
            ["O(n²) allows O(n). Θ(n²) means quadratic growth exactly, not just 'at most quadratic'."],
            "A single loop runs from 1 to n with O(1) work inside. Classify T(n).",
            ["Loop executes n times.", "Each iteration: constant work.", "Total: n · O(1) = O(n).", "Also T(n) ≥ n, so Ω(n).", "Therefore Θ(n)."],
            "**Θ(n)**.",
        ),
        concept(
            "Drop Constants and Lower-Order Terms",
            [
                "Standard simplification rules (from [[3.2 Function Notation and Mapping]] and [[2.9 Indices and Powers]]):",
                "",
                "1. Keep the [[dominant term]].",
                "2. Drop lower-order terms: O(n² + n) = O(n²).",
                "3. Drop constant factors: O(50n) = O(n).",
                "4. log bases change by a constant factor: O(log₂ n) = O(log₁₀ n).",
                "",
                "```text",
                "5n³ + 200n² + 999   →   O(n³)",
                "100 log n + n       →   O(n)",
                "```",
            ],
            "failure", "Keeping constants in final Big-O",
            ["O(2ⁿ) and O(3ⁿ) are both exponential, but 3ⁿ grows much faster — do not collapse different bases when comparing exponentials."],
            "Simplify O(4n log n + n + 1000) to standard form.",
            ["Identify dominant term: 4n log n.", "Drop n and 1000.", "Drop coefficient 4.", "Result: O(n log n).", "If the loop structure forces n log n work, this is also Θ(n log n)."],
            "**O(n log n)**.",
        ),
        concept(
            "CS Case Study — Comparing Two Search Methods",
            [
                "**Linear search** on n items: worst case n comparisons → **O(n)**.",
                "",
                "**Binary search** on sorted n items: halve each step → about log₂ n steps → **O(log n)**.",
                "",
                "For n = 1,048,576 (2²⁰), linear may need ~1M steps; binary needs ~20.",
                "",
                "This is why sorted arrays enable fast lookup in databases and standard libraries.",
            ],
            "example", "Real library behaviour",
            ["Python's `list.index` is O(n). `bisect` on a sorted list is O(log n). Choosing the wrong structure costs orders of magnitude at scale."],
            "Which is faster for n = 1,000,000: O(n) or O(log n)? By roughly what factor?",
            ["O(log n) is faster for large n.", "n / log₂(1,000,000) ≈ 1,000,000 / 20 ≈ 50,000.", "Binary search could be tens of thousands of times fewer steps.", "Constants matter for small n, but not asymptotically."],
            "**O(log n)** is vastly faster; roughly 50,000× fewer steps at this n.",
        ),
    ],
    "why": "Asymptotic notation works because for large n, multiplying by constants or adding smaller terms does not change the **qualitative** comparison. If algorithm A is Θ(n²) and B is Θ(n log n), B eventually wins no matter what hardware you use. This idea comes from [[9.1 Limits and Continuity]] — we study behaviour as n → ∞. Inequalities from [[2.7 Inequalities]] justify the bounding definitions of O, Ω, and Θ.",
    "mistakes": [
        "Confusing O (upper bound) with Θ (tight bound).",
        "Including constant factors in final answers, e.g. O(5n) instead of O(n).",
        "Claiming O(1) for an algorithm that loops over input size.",
        "Using Big-O on best case when the question asks worst case.",
        "Comparing two functions at one small n instead of asymptotically.",
        "Forgetting that O(log n) base changes are equivalent up to constants.",
    ],
    "failure": "If your bound seems too good, check whether you counted all loops and recursive calls. Missing a hidden nested loop is the most common reason students claim O(n) for an O(n²) algorithm.",
    "cs_intro": "Big-O appears everywhere performance matters:",
    "cs_body": [
        "- **Standard library docs**: `sort()` is O(n log n), `dict` lookup average O(1).",
        "- **Interview and code review**: justify data structure choices.",
        "- **Systems design**: predict latency as traffic grows.",
        "- **Database query plans**: explain index vs full table scan.",
        "",
        "Example API choice:",
        "",
        "```python",
        "# O(n) - scan entire list",
        "def find_user_linear(users, target_id):",
        "    for u in users:",
        "        if u.id == target_id:",
        "            return u",
        "",
        "# O(1) average - hash map",
        "users_by_id = {u.id: u for u in users}",
        "user = users_by_id[target_id]",
        "```",
    ],
    "checkpoint": [
        "What question does asymptotic notation answer?",
        "State Big O in one sentence.",
        "State Big Theta in one sentence.",
        "What is the dominant term in 10n² + 3n + 7?",
        "Why are constants dropped in Big-O?",
        "Is 5n = O(n)? Explain briefly.",
        "What is Ω(n) saying about an algorithm?",
        "When is Θ(n log n) tighter than O(n²)?",
        "Link linear vs binary search to Big-O.",
        "Which module topic justifies 'as n → ∞'?",
    ],
    "mini_quiz": [
        "Simplify O(3n² + 5n + 100).",
        "Give O, Ω, and Θ for a single loop over n with O(1) body.",
        "True or false: O(n) means exactly n steps.",
        "Which grows faster: n log n or n²? (for large n)",
        "Prove 10n + 3 = O(n) informally.",
        "Why is binary search O(log n)?",
        "Spot the error: 'Two nested loops → O(n)'.",
        "Classify O(1) vs O(n) for hash table lookup vs list scan.",
        "Name one CS API and its typical Big-O.",
        "Which earlier topic gives the definition of inequalities used in O?",
    ],
    "pass_gate": [
        "classify a loop nest as O, Ω, or Θ",
        "drop constants and lower-order terms correctly",
        "compare two growth rates for large n",
        "explain one real algorithm's complexity in plain English",
    ],
    "worked": [
        {"title": "Find Dominant Term", "q": "Simplify T(n) = 6n² + 100n + 50.", "steps": ["List terms.", "For large n, n² dominates.", "Drop 100n and 50.", "Drop coefficient 6."], "answer": "O(n²)"},
        {"title": "Prove Big-O", "q": "Show 4n + 7 = O(n).", "steps": ["Need 4n + 7 ≤ cn.", "Try c = 5: 4n + 7 ≤ 5n when 7 ≤ n.", "n₀ = 7 works."], "answer": "O(n) with c = 5, n₀ = 7"},
        {"title": "Classify Loop", "q": "for i in range(n): for j in range(n): work()", "steps": ["Outer runs n times.", "Inner runs n times each.", "Total iterations n × n = n².", "Constant work per iteration."], "answer": "Θ(n²)"},
        {"title": "Spot the Mistake", "q": "Student says: 'Loop runs n times with 10 ops inside → O(10n) → keep 10 → O(10n)'. Fix it.", "steps": ["Constants are dropped in Big-O.", "10n is still linear growth.", "Correct answer: O(n)."], "answer": "O(n), not O(10n)"},
        {"title": "CS — Binary vs Linear", "q": "Compare O(n) linear scan vs O(log n) binary search for n = 2¹⁶.", "steps": ["Linear: up to 65536 comparisons.", "Binary: about 16 comparisons.", "Ratio ≈ 4096."], "answer": "Binary search ~4096× fewer steps"},
        {"title": "Tight Bound", "q": "Merge sort does Θ(n log n). Is O(n²) acceptable? Is it best?", "steps": ["O(n²) is a valid upper bound.", "It is not tight — merge sort is faster than quadratic.", "Prefer Θ(n log n) when known."], "answer": "Valid but loose; use Θ(n log n)"},
    ],
    "self_check": [
        "why O ignores constants",
        "difference between O and Θ",
        "how nested loops affect growth",
        "why binary search is logarithmic",
    ],
    "practice_sections": [
        ["Define [[Big O]] in your own words.", "Define [[Big Theta]].", "Define [[Big Omega]].", "Define [[asymptotic growth]].", "Define [[dominant term]]."],
        ["Simplify O(5n³ + 2n + 1).", "Simplify O(n log n + n).", "Classify: one loop, n iterations, O(1) body.", "Classify: two nested loops over n.", "Classify: halving n each step until 1.", "Prove 3n + 4 = O(n) informally."],
        ["Error: 'O(2n) is different from O(n)'. Explain.", "Error: 'Best case O(1) so algorithm is O(1)'. Fix.", "Error: 'O(n² + n) = O(n)'. Fix.", "Error: claiming O(log n) for unsorted search."],
        ["Rank: O(1), O(log n), O(n), O(n log n), O(n²), O(2ⁿ).", "T(n) = n/2 + 10. Give O and Θ.", "Which dominates: 1000n vs n² for n = 10⁶?", "Write cost of binary search in words and Big-O."],
        ["Why does Python dict lookup claim average O(1)?", "Name a standard library operation that is O(n log n).", "Explain why interviewers ask Big-O.", "Compare hash lookup vs list scan for 1M users.", "When would O(n²) block a production system?"],
    ],
    "practice_answers": [
        ["f grows no faster than c·g for large n.", "f bounded above and below by constant multiples of g.", "f grows at least as fast as c·g.", "behaviour as n → ∞.", "highest-order term controlling growth."],
        ["O(n³)", "O(n log n)", "Θ(n)", "Θ(n²)", "Θ(log n)", "4n + 4 ≤ 5n for n ≥ 4"],
        ["Constants dropped — both O(n).", "Must state worst-case unless asked; e.g. hash worst O(n).", "Dominant term is n² → O(n²).", "Unsorted array needs scan → Ω(n)."],
        ["O(1) < O(log n) < O(n) < O(n log n) < O(n²) < O(2ⁿ)", "O(n), Θ(n)", "n² dominates", "Repeated halving → O(log n)"],
        ["Hash maps index by key directly on average.", "Sorting (e.g. sorted(), list.sort).", "Predict scalability before deployment.", "Dict O(1) avg vs list O(n) scan.", "Large n with tight latency budget (e.g. n=10⁶, n²=10¹² ops)."],
    ],
    "mastery_b": ["Simplify O(2n² + 50n + 300).", "Classify: loop i=0..n-1, inner j=0..i.", "Show n + log n = O(n).", "Compare O(n log n) vs O(n²) for n → ∞.", "Give Θ bound for n steps each with O(1) work.", "Binary search on 1024 items: max comparisons?"],
    "mastery_c": ["Student: nested loop is O(n) because inner runs 'only sometimes'. When wrong?", "Student: O(5n²) final answer. Fix.", "Student uses best-case for hash table. Correct approach?"],
    "mastery_d": ["Prove 7n + 2 = O(n) with c and n₀.", "T(n) = 3n log n + n. State O, Ω, Θ.", "Why is comparison sort Ω(n log n)?", "Graph: n=100, which is larger n² or 100n?", "Explain dominant term in 2ⁿ + n⁵."],
    "mastery_e": ["Why is O(log n) important for databases?", "Give CS example of O(n²) causing slowness.", "Explain Big-O to a junior dev in two sentences.", "Link to [[2.7 Inequalities]] in defining O.", "When is loose O(n²) still useful?"],
    "mastery_answers": [
        "f bounded above by c·g(n).", "f grows at least as fast as c·g(n).", "f sandwiched between c₁g and c₂g.", "growth as n → ∞.", "leading term at large n.",
        "O(n²)", "Outer n, inner average n/2 → O(n²)", "log n absorbed by n", "n log n grows slower than n²", "Θ(n)", "10 (log₂ 1024)",
        "If inner always runs n times → Θ(n²)", "Drop 5 → O(n²)", "State average vs worst; worst O(n) for hash chains",
        "7n+2 ≤ 8n for n≥2; c=8,n₀=2", "O(n log n), Ω(n log n), Θ(n log n)", "Must distinguish n! orderings with comparisons", "n²=10000 > 100n=10000 tie; n² grows faster eventually", "2ⁿ dominates n⁵ for large n",
        "Indexes enable log-depth tree lookup", "Naive all-pairs comparison", "Upper bound on growth ignoring constants", "f(n)≤cg(n) is an inequality", "When only upper limit needed for safety",
    ],
    "glossary_builds": {"Big O": "2.7 Inequalities", "Big Theta": "Big O", "Big Omega": "Big O", "asymptotic growth": "9.1 Limits and Continuity", "dominant term": "2.9 Indices and Powers"},
    "glossary_cs": {
        "Big O": "Documenting worst-case API cost so callers know scalability limits.",
        "Big Theta": "Stating tight bounds when proving algorithm performance matches lower bound.",
        "Big Omega": "Proving impossibility results — no algorithm can beat Ω(n log n) for comparison sort.",
        "asymptotic growth": "Reasoning about cloud costs and latency as user base scales.",
        "dominant term": "Identifying which loop nest controls runtime in profiling.",
    },
    "cs_one_liner": "Complexity notation predicts how programs scale.",
    "plain_short": "Classify algorithm growth rates.",
    "cum_questions": ["Define Big O and give O(n² + n) simplified.", "Classify two nested loops over n."],
})

# Due to length, remaining 11 topics follow same structure — appended in part 2
exec(open("/home/Marau/Marau/University/Maths for CS/scripts/module_10_topics_part2.py").read())
