"""Topic data for Module 08 Probability and Statistics."""

TOPICS = []

# =============================================================================
# 8.1 Probability Basics
# =============================================================================
TOPICS.append({
    "id": "8.1",
    "title": "Probability Basics",
    "tags": "#maths/probability #maths/statistics #cs/randomness",
    "prereq": ["7.12 Numerical Stability in Linear Algebra", "1.6 Fractions", "1.7 Decimals and Percentages"],
    "used_later": ["8.2 Conditional Probability", "8.7 Descriptive Statistics", "10.2 Algorithm Complexity Case Studies"],
    "next": "8.2 Conditional Probability",
    "plain": "Probability measures how likely an [[event]] is to happen, on a scale from 0 (impossible) to 1 (certain).\n\nAt its heart, probability is a fraction: favourable outcomes over total equally likely outcomes. This is exactly the idea from [[1.6 Fractions]] — `3/4` means 3 out of 4 equal parts. When you write `75%`, you are using [[1.7 Decimals and Percentages]] to say the same thing.\n\nBefore conditional probability, Bayes, or machine learning, you need to name the [[sample space]], list the [[outcome]]s, and compute simple probabilities with fractions and complements.",
    "everyday": "If a fair six-sided die is rolled, the probability of getting a 4 is 1 out of 6 equally likely faces — that is `1/6`, about 0.167, or about 16.7%.",
    "plain_short": "Measure how likely events are using fractions and the 0-to-1 scale.",
    "cs_one_liner": "Reliability, ML predictions, simulations, and randomised algorithms use probability.",
    "terms": [
        ("event", "a collection of outcomes you care about — the thing whose likelihood you measure."),
        ("outcome", "one single possible result of a random experiment — the smallest indivisible result."),
        ("sample space", "the complete set of all possible outcomes for an experiment."),
        ("probability scale", "the rule that probabilities lie between 0 and 1, where 0 means impossible and 1 means certain."),
        ("complement", "the event that an outcome does NOT belong to A; written A' or Aᶜ, with P(A') = 1 − P(A)."),
    ],
    "concepts": [
        {
            "title": "Probability as a Fraction",
            "body": [
                "The classical definition connects probability directly to [[1.6 Fractions]]:",
                "",
                "$$P(A) = \\frac{\\text{favourable outcomes}}{\\text{total equally likely outcomes}}$$",
                "",
                "Example: a fair coin has sample space `{H, T}`.",
                "",
                "```text",
                "P(Heads) = 1/2",
                "```",
                "",
                "The numerator counts outcomes in the [[event]]. The denominator counts all outcomes in the [[sample space]].",
                "",
                "This only works when outcomes are **equally likely** — a loaded coin needs a different approach.",
            ],
            "callout": "important",
            "callout_title": "Fraction first",
            "callout_body": ["Always write probability as a fraction before converting to a decimal or percentage."],
            "q": "A fair die is rolled. What is P(even number)?",
            "steps": [
                "List the sample space: {1, 2, 3, 4, 5, 6}. Total = 6.",
                "Even outcomes: {2, 4, 6}. Favourable = 3.",
                "```text",
                "P(even) = 3/6 = 1/2",
                "```",
            ],
            "answer": "**P(even) = 1/2** (same as 0.5 or 50%).",
        },
        {
            "title": "The Probability Scale",
            "body": [
                "The [[probability scale]] runs from 0 to 1:",
                "",
                "```text",
                "0     impossible     P = 0",
                "0.25  unlikely       P = 1/4",
                "0.5   equally likely P = 1/2",
                "0.75  likely        P = 3/4",
                "1     certain        P = 1",
                "```",
                "",
                "Every probability must satisfy `0 ≤ P(A) ≤ 1`.",
                "",
                "Using [[1.7 Decimals and Percentages]], multiply by 100 to communicate:",
                "",
                "```text",
                "0.25 = 25%    3/4 = 0.75 = 75%",
                "```",
            ],
            "callout": "warning",
            "callout_title": "No negative probabilities",
            "callout_body": ["Probabilities cannot be negative or greater than 1. If your calculation gives 1.2, something is wrong."],
            "q": "Convert P = 2/5 to a decimal and a percentage.",
            "steps": [
                "```text",
                "2/5 = 0.4",
                "```",
                "Multiply by 100 for percent:",
                "```text",
                "0.4 × 100 = 40%",
                "```",
            ],
            "answer": "**0.4** or **40%**.",
        },
        {
            "title": "Sample Space and Outcomes",
            "body": [
                "Before computing anything, name the objects:",
                "",
                "- [[sample space]] S — all possible results",
                "- [[outcome]] — one element of S",
                "- [[event]] — a subset of S (one or more outcomes)",
                "",
                "Example: two coin flips.",
                "",
                "```text",
                "S = {HH, HT, TH, TT}    — 4 outcomes",
                "Event 'at least one Head' = {HH, HT, TH}    — 3 outcomes",
                "```",
                "",
                "Listing the sample space prevents double-counting and missing cases.",
            ],
            "callout": "tip",
            "callout_title": "List before you calculate",
            "callout_body": ["Write the sample space on paper. Many probability errors come from an incomplete list."],
            "q": "A bag has 3 red and 2 blue balls. One ball is drawn. List S and the event 'red'.",
            "steps": [
                "Label balls: R1, R2, R3, B1, B2.",
                "```text",
                "S = {R1, R2, R3, B1, B2}",
                "Event red = {R1, R2, R3}",
                "```",
            ],
            "answer": "**S has 5 outcomes; event red has 3 outcomes.**",
        },
        {
            "title": "Complement Rule",
            "body": [
                "The [[complement]] of event A is 'not A'.",
                "",
                "$$P(A') = 1 - P(A)$$",
                "",
                "This is useful when 'not A' is easier to count than A.",
                "",
                "Example: P(at least one Head in 2 flips) = 1 − P(no Heads).",
                "",
                "```text",
                "P(no Heads) = P(TT) = 1/4",
                "P(at least one Head) = 1 - 1/4 = 3/4",
                "```",
                "",
                "The complement rule connects to [[1.7 Decimals and Percentages]]: if 25% fail, then 75% pass.",
            ],
            "callout": "example",
            "callout_title": "Pass rate connection",
            "callout_body": ["If 18/20 tests pass, P(pass) = 9/10 = 90%. P(fail) = 1 - 0.9 = 10%."],
            "q": "P(rain) = 0.35. What is P(no rain)?",
            "steps": [
                "```text",
                "P(no rain) = 1 - 0.35 = 0.65",
                "```",
            ],
            "answer": "**0.65** or **65%**.",
        },
        {
            "title": "Adding Probabilities of Mutually Exclusive Events",
            "body": [
                "Two events are **mutually exclusive** if they cannot both happen.",
                "",
                "If A and B share no outcomes:",
                "",
                "$$P(A \\text{ or } B) = P(A) + P(B)$$",
                "",
                "Example: one die roll.",
                "",
                "```text",
                "P(1) = 1/6,  P(2) = 1/6",
                "P(1 or 2) = 1/6 + 1/6 = 2/6 = 1/3",
                "```",
                "",
                "> Do not add if events overlap — that double-counts shared outcomes.",
            ],
            "callout": "failure",
            "callout_title": "Overlap warning",
            "callout_body": ["P(Heart or King) on a card draw is NOT P(Heart) + P(King) because the King of Hearts is counted twice."],
            "q": "A fair die: P(1 or 6)?",
            "steps": [
                "Events {1} and {6} do not overlap.",
                "```text",
                "P(1 or 6) = 1/6 + 1/6 = 2/6 = 1/3",
                "```",
            ],
            "answer": "**1/3**.",
        },
        {
            "title": "Probability in CS Contexts",
            "body": [
                "Programs use probability for:",
                "",
                "- test pass rates (fractions from [[1.6 Fractions]])",
                "- random number generators (uniform outcomes in S)",
                "- hash collision estimates",
                "- Monte Carlo simulation",
                "",
                "```python",
                "import random",
                "outcomes = ['pass', 'fail']",
                "result = random.choice(outcomes)  # P(pass) = P(fail) = 0.5 if fair",
                "```",
                "",
                "A random choice from a list assumes each [[outcome]] is equally likely unless weights are given.",
            ],
            "callout": "example",
            "callout_title": "CS connection",
            "callout_body": ["`random.random()` returns a value in [0, 1) — directly tied to the probability scale."],
            "q": "A function returns True with probability 3/8. In 800 calls, how many True results do you expect?",
            "steps": [
                "Expected count = probability × trials.",
                "```text",
                "(3/8) × 800 = 300",
                "```",
            ],
            "answer": "**300** True results expected (actual count will vary).",
        },
    ],
    "why": "Probability works because it counts equally likely parts of a whole — the same structure as [[1.6 Fractions]]. The [[probability scale]] keeps answers between 0 and 1, and [[1.7 Decimals and Percentages]] lets you communicate results. The [[complement]] rule uses the fact that something either happens or it does not: P(A) + P(A') = 1.",
    "mistakes": [
        "Dividing by the wrong total — count all outcomes in the sample space, not just the ones you like.",
        "Adding probabilities of overlapping events without subtracting the intersection.",
        "Forgetting that P = 1 means certain, not 'very likely'.",
        "Converting to decimal too early and losing the exact fraction.",
        "Assuming outcomes are equally likely when they are not (loaded die, biased sample).",
        "Using percentages above 100% or below 0%.",
    ],
    "failure": "Computing P(Heart or King) as 13/52 + 4/52 = 17/52 is wrong. The King of Hearts is in both events. Correct: 16/52.",
    "cs_intro": "Probability appears wherever programs handle uncertainty:",
    "cs_body": [
        "- **Randomised algorithms**: Las Vegas and Monte Carlo methods use P(success).",
        "- **Hash tables**: collision probability guides bucket sizing.",
        "- **Load testing**: P(request fails) drives reliability targets.",
        "- **ML classifiers**: output scores are often interpreted as probabilities.",
        "",
        "```python",
        "# Simulate fair coin — empirical probability approaches 1/2",
        "heads = sum(random.choice(['H','T']) == 'H' for _ in range(10000))",
        "print(heads / 10000)  # close to 0.5",
        "```",
    ],
    "checkpoint": [
        "What is a sample space?",
        "Write P(even) for a fair die as a fraction.",
        "Convert 3/8 to a percentage.",
        "What is the complement of event A?",
        "If P(A) = 0.7, what is P(A')?",
        "When can you add P(A) + P(B)?",
        "List the sample space for one coin flip.",
        "Why must probabilities stay between 0 and 1?",
        "Give one CS example using probability.",
        "How does probability connect to fractions?",
    ],
    "mini_quiz": [
        "Define [[event]] in your own words.",
        "Define [[outcome]] in your own words.",
        "Define [[sample space]] in your own words.",
        "Define [[probability scale]] in your own words.",
        "Define [[complement]] in your own words.",
        "P(fair coin Heads)?",
        "P(die shows 5)?",
        "P(not 5) on a fair die?",
        "Convert 7/20 to a percent.",
        "Explain one CS use of probability.",
    ],
    "pass_gate": [
        "compute P(A) as a fraction and convert to decimal/percent",
        "use the complement rule without looking",
        "list a sample space completely for a small experiment",
    ],
    "worked": [
        {"title": "Fraction to Probability", "q": "A deck has 52 cards. P(drawing a Heart)?", "steps": ["Hearts = 13.", "Total = 52.", "```text\nP(Heart) = 13/52 = 1/4\n```"], "answer": "1/4 = 0.25 = 25%"},
        {"title": "Complement", "q": "P(server uptime) = 0.992. P(downtime)?", "steps": ["```text\nP(down) = 1 - 0.992 = 0.008\n```"], "answer": "0.008 = 0.8%"},
        {"title": "Mutually Exclusive Sum", "q": "Fair die: P(2 or 5)?", "steps": ["No overlap.", "```text\n1/6 + 1/6 = 2/6 = 1/3\n```"], "answer": "1/3"},
        {"title": "Two-Stage Sample Space", "q": "Two coins. P(exactly one Head)?", "steps": ["S = {HH, HT, TH, TT}.", "Favourable = {HT, TH}.", "```text\nP = 2/4 = 1/2\n```"], "answer": "1/2"},
        {"title": "CS Simulation", "q": "A/B test: 340 conversions out of 1000. Estimate P(convert).", "steps": ["```text\n340/1000 = 34/100 = 0.34 = 34%\n```"], "answer": "34% conversion rate (empirical probability)", "note": "Empirical probability uses observed frequency — connects to fractions."},
        {"title": "Spot the Mistake", "q": "A learner says P(odd or even on a die) = 1/2 + 1/2 = 1. What is wrong?", "steps": ["Odd and even cover ALL outcomes on a die.", "They are complements, not separate halves.", "Every roll is odd OR even, so P = 1 by definition."], "answer": "The calculation accidentally gives the right answer (1) but for the wrong reason — odd and even partition the sample space."},
    ],
    "practice_sections": [
        ["Define [[event]].", "Define [[outcome]].", "Define [[sample space]].", "Define [[probability scale]].", "Define [[complement]].", "How does probability relate to [[1.6 Fractions]]?"],
        ["Fair coin: P(Tails)?", "Fair die: P(3)?", "Fair die: P(greater than 4)?", "Bag: 4 green, 1 red. P(green)?", "Two coins: P(both Tails)?", "P(at least one Head in 2 flips)?", "Convert 5/8 to decimal and percent.", "P(A)=0.42. P(A')?", "Cards: P(King)?", "Cards: P(not a Heart)?"],
        ["Wrong: P(1 or 2 on die) = 1/6 × 1/6. Fix it.", "Wrong: P(rain) = 1.3. Explain the error.", "Wrong: P(Heart) + P(Spade) = 26/52 on one draw. Fix it.", "Wrong: sample space for die = {1,2,3,4,5}. What's missing?"],
        ["Three coins: list S and P(exactly 2 Heads).", "Die rolled twice: P(sum = 7)? (list approach)", "P(even or prime) on one die roll?", "Spinner: 3 red, 2 blue, 5 yellow sectors. P(not yellow)?", "Explain complement vs mutually exclusive."],
        ["800 requests, 12 fail. Write P(success) as fraction and percent.", "Hash: 64 buckets, uniform hash. P(collision with one other key)? (approx 1/64)", "Why does `random.random() < 0.3` implement 30% chance?", "Monte Carlo: explain estimating π using random points.", "Give one example where assuming equal likelihood is wrong."],
    ],
    "practice_answers": [
        ["An event is a set of outcomes you want to measure.", "An outcome is one possible result.", "The sample space is all possible outcomes.", "The probability scale runs from 0 (impossible) to 1 (certain).", "The complement is 'not A'; P(A') = 1 − P(A).", "Probability equals favourable outcomes over total equally likely outcomes — a fraction."],
        ["1/2", "1/6", "2/6 = 1/3 (outcomes 5,6)", "4/5", "1/4", "3/4 (complement of TT)", "0.625 = 62.5%", "0.58", "4/52 = 1/13", "39/52 = 3/4"],
        ["Add, don't multiply: 1/6 + 1/6 = 1/3.", "Probabilities cannot exceed 1.", "One card is drawn — only one suit. P(Heart OR Spade) = 13/52 + 13/52 = 26/52 = 1/2 only if asking colour on one draw; actually one card can't be both, so 26/52 is correct for red OR black on one draw — learner may have meant Heart AND Spade which is 0.", "Missing outcome 6."],
        ["S has 8 outcomes; favourable HHT, HTH, THH → 3/8.", "36 outcomes; six give sum 7 → 6/36 = 1/6.", "Even {2,4,6} or prime {2,3,5} → {2,3,4,5,6} → 5/6.", "5/10 = 1/2.", "Complement: one event 'not A'. Mutually exclusive: two events with no overlap."],
        ["788/800 = 197/200 = 0.985 = 98.5%.", "Approximately 1/64 for a specific other key.", "random.random() is uniform on [0,1); values below 0.3 occur 30% of the time.", "Random points in a square; ratio inside quarter-circle estimates π/4.", "Loaded die, biased training data, network failures during peak hours."],
    ],
    "mastery_b": ["Fair die: P(less than 3)? (1 mark)", "P(A)=0.18. P(A')? (1 mark)", "Two dice: P(sum is 8)? (2 marks)", "Convert 11/40 to percent. (1 mark)", "Cards: P(Face card)? J,Q,K × 4 suits = 12. (1 mark)"],
    "mastery_c": ["Fix: P(3 or 4 on die) = (1/6)(1/6) = 1/36. (1 mark)", "Fix: P(certain event) = 0. (1 mark)", "Explain why P(A) + P(B) can exceed 1. (2 marks)"],
    "mastery_d": ["Three coins: P(at most one Tail)? (2 marks)", "A system has 0.97 availability. Expected downtime fraction in a year? (1 mark)", "List sample space for drawing two balls with replacement from {R,B}. (2 marks)"],
    "mastery_e": ["1000 users, 47 errors. Write P(no error) as fraction and percent. (2 marks)", "Explain how probability connects to [[1.6 Fractions]] and [[1.7 Decimals and Percentages]]. (2 marks)", "Name one CS system where assuming equal likelihood would be dangerous. (1 mark)"],
    "mastery_answers": [
        "An event is a collection of outcomes whose probability we measure.",
        "An outcome is one possible result of a random experiment.",
        "The sample space is the set of all possible outcomes.",
        "The probability scale assigns 0 to impossible and 1 to certain events.",
        "The complement of A is the event that A does not occur; P(A') = 1 − P(A).",
        "P(<3) = P(1 or 2) = 2/6 = 1/3.",
        "P(A') = 1 − 0.18 = 0.82.",
        "Sum 8: (2,6),(3,5),(4,4),(5,3),(6,2) → 5/36.",
        "11/40 = 0.275 = 27.5%.",
        "P(face) = 12/52 = 3/13.",
        "Should add: 1/6 + 1/6 = 1/3.",
        "Certain event has P = 1, not 0.",
        "When A and B overlap, P(A)+P(B) double-counts P(A∩B).",
        "At most one Tail: HHH, HHT, HTH, THH → 4/8 = 1/2.",
        "Downtime fraction ≈ 1 − 0.97 = 0.03 = 3%.",
        "S = {RR, RB, BR, BB}.",
        "P(no error) = 953/1000 = 95.3%.",
        "Probability is favourable over total — a fraction; multiply by 100 for percent.",
        "Fraud detection, medical diagnosis, or any biased data pipeline.",
    ],
    "glossary_builds": {"event": "1.6 Fractions", "outcome": "1.1 Counting and Number Sense", "sample space": "1.6 Fractions", "probability scale": "1.7 Decimals and Percentages", "complement": "1.6 Fractions"},
    "glossary_cs": {
        "event": "Log events, test failures, and packet drops are all events whose frequency is measured.",
        "outcome": "A single random draw, test run, or packet arrival is one outcome in a simulation.",
        "sample space": "Defining all possible API responses or test results is specifying the sample space.",
        "probability scale": "Classifier confidence scores and reliability targets must stay on the 0-to-1 scale.",
        "complement": "P(failure) = 1 − P(success) is used in SLA and uptime calculations.",
    },
    "cum_marks": 5,
    "cum_questions": [
        "Define sample space and give an example with 4 outcomes. (1 mark)",
        "Fair die: P(not 6) as fraction and percent. (1 mark)",
        "Explain complement rule with one example. (1 mark)",
        "Two coins: P(both Heads)? (1 mark)",
        "Why is probability described as a fraction from [[1.6 Fractions]]? (1 mark)",
    ],
})

# =============================================================================
# 8.2 Conditional Probability
# =============================================================================
TOPICS.append({
    "id": "8.2",
    "title": "Conditional Probability",
    "tags": "#maths/probability #maths/statistics #cs/inference",
    "prereq": ["8.1 Probability Basics", "1.6 Fractions"],
    "used_later": ["8.3 Bayes Theorem", "8.10 Bayesian Inference"],
    "next": "8.3 Bayes Theorem",
    "plain": "[[Conditional probability]] answers: **given that B happened, what is the chance of A?**\n\nNotation: `P(A|B)` read as 'P of A [[given]] B'.\n\nThis shrinks the [[sample space]] from [[8.1 Probability Basics]] to only outcomes where B is true, then counts how many also satisfy A. The fraction structure from [[1.6 Fractions]] still applies — but the denominator is now P(B), not the full sample space.\n\n[[Independence]] means extra information changes nothing. [[Dependence]] means the 'given' clause matters.",
    "everyday": "If you know a card drawn is red, the probability it is a Heart changes from 13/52 to 13/26 — the sample space shrank to red cards only.",
    "plain_short": "Update probability when extra information is known.",
    "cs_one_liner": "Spam filters, risk models, and diagnostics use conditional probability.",
    "terms": [
        ("conditional probability", "the probability of A given that B has occurred, written P(A|B)."),
        ("given", "the condition that restricts attention to outcomes where an event B is true."),
        ("joint probability", "the probability that both A and B happen: P(A ∩ B)."),
        ("independence", "when P(A|B) = P(A) — knowing B does not change the chance of A."),
        ("dependence", "when knowing B changes P(A) — the events influence each other."),
    ],
    "concepts": [
        {
            "title": "The Conditional Formula",
            "body": [
                "$$P(A|B) = \\frac{P(A \\cap B)}{P(B)} \\quad \\text{provided } P(B) > 0$$",
                "",
                "Read: restrict to outcomes where B is true, then find the fraction that also satisfies A.",
                "",
                "This builds directly on [[8.1 Probability Basics]]: numerator and denominator are still fractions from [[1.6 Fractions]].",
                "",
                "```text",
                "P(Heart | Red) = P(Heart and Red) / P(Red)",
                "               = (13/52) / (26/52)",
                "               = 13/26 = 1/2",
                "```",
            ],
            "callout": "important",
            "callout_title": "Denominator is P(B)",
            "callout_body": ["The 'given B' clause means B is the new whole — the new denominator."],
            "q": "Fair die. Given the roll is even, what is P(greater than 4)?",
            "steps": [
                "Given even: sample space {2, 4, 6}.",
                "Greater than 4 among evens: {6}.",
                "```text",
                "P(>4 | even) = 1/3",
                "```",
            ],
            "answer": "**1/3**.",
        },
        {
            "title": "Joint Probability and the Multiplication Rule",
            "body": [
                "[[Joint probability]] P(A ∩ B) means both events happen.",
                "",
                "Rearranging the conditional formula:",
                "",
                "$$P(A \\cap B) = P(A|B) \\times P(B) = P(B|A) \\times P(A)$$",
                "",
                "Example: two cards without replacement.",
                "",
                "```text",
                "P(both Hearts) = P(H2|H1) × P(H1)",
                "               = (12/51) × (13/52)",
                "```",
            ],
            "callout": "warning",
            "callout_title": "Order matters without replacement",
            "callout_body": ["P(A|B) and P(B|A) are usually different — do not swap them blindly."],
            "q": "P(rain) = 0.3, P(late | rain) = 0.6. P(rain AND late)?",
            "steps": [
                "```text",
                "P(rain ∩ late) = 0.6 × 0.3 = 0.18",
                "```",
            ],
            "answer": "**0.18**.",
        },
        {
            "title": "Independence",
            "body": [
                "Events A and B are [[independent]] if:",
                "",
                "$$P(A|B) = P(A) \\quad \\text{and} \\quad P(B|A) = P(B)$$",
                "",
                "Equivalently: `P(A ∩ B) = P(A) × P(B)`.",
                "",
                "Two fair coin flips: first result does not affect the second.",
                "",
                "```text",
                "P(H2 | H1) = P(H2) = 1/2",
                "```",
            ],
            "callout": "tip",
            "callout_title": "Test for independence",
            "callout_body": ["Check whether P(A|B) equals P(A). If yes, B gives no information about A."],
            "q": "Fair coin flipped twice. Are 'first Head' and 'second Head' independent?",
            "steps": [
                "P(H2) = 1/2.",
                "P(H2 | H1) = 1/2.",
                "They are equal → independent.",
            ],
            "answer": "**Yes, independent.**",
        },
        {
            "title": "Dependence",
            "body": [
                "[[Dependence]] means the [[given]] information changes the probability.",
                "",
                "Drawing cards without replacement: P(second Heart | first Heart) = 12/51 ≠ 13/52.",
                "",
                "Medical testing: P(disease | positive test) ≠ P(disease) — the test result is informative.",
                "",
                "Dependence is the normal case in real data. Independence is a simplifying assumption.",
            ],
            "callout": "example",
            "callout_title": "Spam filter preview",
            "callout_body": ["P(spam | contains 'winner') is much higher than P(spam) — the word 'winner' creates dependence."],
            "q": "P(disease) = 0.01, P(positive | disease) = 0.95, P(positive | no disease) = 0.05. Is 'positive test' independent of disease?",
            "steps": [
                "P(positive | disease) = 0.95.",
                "P(positive | no disease) = 0.05.",
                "These differ greatly → dependent.",
            ],
            "answer": "**No — strongly dependent.**",
        },
        {
            "title": "Tree Diagrams and Tables",
            "body": [
                "Tree diagrams show sequential conditionals:",
                "",
                "```text",
                "        rain(0.3)",
                "       /        \\",
                "   late(0.6)  on-time(0.4)",
                "       \\        /",
                "        no rain(0.7)",
                "       /        \\",
                "   late(0.1)  on-time(0.9)",
                "```",
                "",
                "Multiply along branches for joint probabilities.",
                "",
                "Two-way tables organise joint and conditional counts — essential before [[8.3 Bayes Theorem]].",
            ],
            "callout": "tip",
            "callout_title": "Multiply along branches",
            "callout_body": ["P(rain AND late) = 0.3 × 0.6 = 0.18 from the tree."],
            "q": "From the tree above, P(late)?",
            "steps": [
                "P(late) = P(rain and late) + P(no rain and late).",
                "```text",
                "= 0.3×0.6 + 0.7×0.1 = 0.18 + 0.07 = 0.25",
                "```",
            ],
            "answer": "**0.25**.",
        },
        {
            "title": "Conditional Probability in CS",
            "body": [
                "Spam filters compute P(spam | email content).",
                "",
                "Intrusion detection: P(attack | log pattern).",
                "",
                "Recommendation: P(click | user history).",
                "",
                "```python",
                "# Naive idea: count-based conditional",
                "p_spam_given_word = spam_with_word / total_with_word",
                "```",
                "",
                "Every 'given' clause in code is a conditional probability in disguise.",
            ],
            "callout": "example",
            "callout_title": "CS connection",
            "callout_body": ["Bayesian spam filters in [[8.3 Bayes Theorem]] multiply many P(word | spam) terms."],
            "q": "100 emails contain 'free'; 80 are spam. Estimate P(spam | 'free').",
            "steps": [
                "```text",
                "P(spam | 'free') ≈ 80/100 = 0.8",
                "```",
            ],
            "answer": "**0.8** (empirical estimate).",
        },
    ],
    "why": "Conditional probability works by restricting the [[sample space]] from [[8.1 Probability Basics]] to the 'given' event, then applying the fraction rule from [[1.6 Fractions]]. The multiplication rule follows from rearranging one formula. Independence is the special case where conditioning changes nothing.",
    "mistakes": [
        "Confusing P(A|B) with P(B|A) — they are different unless P(A) = P(B).",
        "Using the full sample space as denominator instead of P(B).",
        "Assuming independence without checking.",
        "Multiplying P(A) × P(B) when events are dependent.",
        "Forgetting P(B) > 0 is required for P(A|B).",
        "Adding conditionals instead of using the formula.",
    ],
    "failure": "P(rain | wet ground) is not the same as P(wet ground | rain). Wet ground can have other causes.",
    "cs_intro": "Conditional probability powers any system that updates beliefs from evidence:",
    "cs_body": [
        "- **Spam filters**: P(spam | word frequencies)",
        "- **Medical diagnostics**: P(disease | test result)",
        "- **Network security**: P(breach | anomaly pattern)",
        "- **Recommendation engines**: P(purchase | browsing history)",
    ],
    "checkpoint": [
        "What does P(A|B) mean in words?",
        "Write the formula for P(A|B).",
        "What is joint probability?",
        "When are A and B independent?",
        "P(A)=0.4, P(B)=0.5, independent. P(A and B)?",
        "Why is P(A|B) ≠ P(B|A) in general?",
        "Draw a two-branch tree for one coin flip.",
        "Give one dependent real-world pair of events.",
        "How does conditional probability shrink the sample space?",
        "Give one CS example.",
    ],
    "mini_quiz": [
        "Define [[conditional probability]].",
        "Define [[given]].",
        "Define [[joint probability]].",
        "Define [[independence]].",
        "Define [[dependence]].",
        "P(A|B) formula?",
        "P(A)=0.3, P(B)=0.4, independent. P(A∩B)?",
        "Cards: P(King | Red)?",
        "Are two die rolls independent?",
        "Explain one CS use.",
    ],
    "pass_gate": [
        "compute P(A|B) from a table or tree",
        "apply the multiplication rule",
        "decide whether two events are independent",
    ],
    "worked": [
        {"title": "Basic Conditional", "q": "Bag: 3R, 2B. One drawn, known Red. P(R again if second draw without replacement)?", "steps": ["After first Red: 2R, 2B remain.", "```text\nP(R2|R1) = 2/4 = 1/2\n```"], "answer": "1/2"},
        {"title": "Multiplication Rule", "q": "P(A)=0.5, P(B|A)=0.4. P(A and B)?", "steps": ["```text\nP(A∩B) = 0.4 × 0.5 = 0.2\n```"], "answer": "0.2"},
        {"title": "Independence Check", "q": "P(A)=0.3, P(A|B)=0.3. Independent?", "steps": ["P(A|B) = P(A).", "Yes."], "answer": "Independent"},
        {"title": "Two-Way Table", "q": "100 emails: 60 spam, 40 ham. 50 spam contain 'free', 5 ham contain 'free'. P(spam | 'free')?", "steps": ["Total with 'free' = 55.", "```text\nP(spam|'free') = 50/55 ≈ 0.909\n```"], "answer": "≈ 0.909"},
        {"title": "CS Transfer", "q": "IDS: P(attack)=0.02, P(alert|attack)=0.9, P(alert|no attack)=0.01. P(alert)?", "steps": ["```text\nP(alert) = 0.9×0.02 + 0.01×0.98 = 0.018 + 0.0098 = 0.0278\n```"], "answer": "≈ 0.0278"},
        {"title": "Spot the Mistake", "q": "Learner says P(A|B) = P(B|A). Give a counterexample.", "steps": ["Medical test: P(positive|disease) = 0.95.", "P(disease|positive) is much smaller when disease is rare.", "The two conditionals differ."], "answer": "P(A|B) and P(B|A) are generally not equal."},
    ],
    "practice_sections": [
        ["Define [[conditional probability]].", "Define [[given]].", "Define [[joint probability]].", "Define [[independence]].", "Define [[dependence]].", "State the formula for P(A|B)."],
        ["P(A|B) when P(A∩B)=0.12, P(B)=0.4.", "P(A∩B) when P(A|B)=0.5, P(B)=0.6.", "Cards: P(Ace | Spade)?", "Die: P(6 | even)?", "Independent: P(A)=0.2, P(B)=0.5. P(A∩B)?", "From tree: rain 0.2, late|rain 0.5, late|no rain 0.1. P(late)?", "P(A|B)=0.7, P(B)=0.3. P(A∩B)?", "Are successive fair coin flips independent?"],
        ["Wrong: P(A|B) = P(B|A). Explain.", "Wrong: P(A and B) = P(A) + P(B) for independent events. Fix.", "Wrong: P(King|Red) = 4/52. Fix.", "Wrong: independence means A and B cannot both happen."],
        ["Two cards without replacement: P(both Aces)?", "Table: 200 users — 120 mobile, 80 desktop; 90 mobile clicked, 20 desktop clicked. P(click|mobile)?", "Verify independence: P(A)=0.4, P(B)=0.5, P(A∩B)=0.2.", "Three-way: P(A)=0.5, P(B|A)=0.6, P(C|A,B)=0.8. P(A,B,C)?"],
        ["Spam: 70% of 1000 emails spam; 60% of spam has link. P(link|spam)?", "Security: explain P(breach|anomaly) vs P(anomaly|breach).", "A/B: version B has 8% conversion, version A 5%. Is this a conditional probability question? Explain.", "Write Python pseudocode for empirical P(spam|word)."],
    ],
    "practice_answers": [
        ["Probability of A given B occurred.", "The condition restricting to event B.", "Probability both A and B occur.", "P(A|B)=P(A); knowing B doesn't change A.", "Knowing B changes P(A).", "P(A|B) = P(A∩B)/P(B)."],
        ["0.12/0.4 = 0.3", "0.3", "1/13 (one Ace of Spades in 13 Spades)", "1/3", "0.1", "0.2×0.5 + 0.8×0.1 = 0.18", "0.21", "Yes"],
        ["Only equal in special cases; generally different.", "Multiply: 0.2×0.5=0.1.", "Given Red: 26 cards, 2 Kings → 2/26=1/13.", "Independent events CAN both happen; they just don't affect each other."],
        ["(4/52)×(3/51) = 12/2652 = 1/221", "90/120 = 0.75", "0.4×0.5=0.2=P(A∩B) → independent", "0.5×0.6×0.8=0.24"],
        ["0.6", "First is what we want after seeing anomaly; second is how often anomaly occurs during breach.", "Compares P(convert|B) vs P(convert|A) — conditional on version.", "count_spam_with_word / count_all_with_word"],
    ],
    "mastery_b": ["P(A∩B)=0.15, P(B)=0.5. P(A|B)? (1 mark)", "Independent: P(A)=0.25, P(B)=0.8. P(A∩B)? (1 mark)", "Cards: P(Queen | Face)? (2 marks)", "P(late)=0.2, P(late|rain)=0.5, P(rain)=0.3. Use tree to find P(rain|late)? (2 marks — preview Bayes)"],
    "mastery_c": ["Fix: P(A|B) = P(A)/P(B). (1 mark)", "Explain why assuming independence for card draws without replacement is wrong. (2 marks)", "Wrong: P(spam|'free') = P('free'|spam). Identify error. (1 mark)"],
    "mastery_d": ["Two draws without replacement from 5R,3B: P(both Red)? (2 marks)", "Contingency table: compute P(A|B) and P(B|A) and show they differ. (2 marks)", "Prove: if independent, P(A|B)=P(A). (1 mark)"],
    "mastery_e": ["1000 logs: 50 attacks, 45 alerts during attack, 10 alerts otherwise. P(attack|alert)? (2 marks)", "Explain how spam filtering uses conditional probability. (2 marks)", "Name one case where assuming independence causes a bug. (1 mark)"],
    "mastery_answers": [
        "Probability of A given B has occurred.",
        "The conditioning event B that restricts the sample space.",
        "Probability that both A and B occur together.",
        "Events where knowing B does not change P(A).",
        "Events where knowing B changes P(A).",
        "P(A|B) = 0.15/0.5 = 0.3.",
        "0.25 × 0.8 = 0.2.",
        "Face: 12 cards; Queens: 4 → 4/12 = 1/3.",
        "P(rain|late) = P(rain∩late)/P(late) = 0.15/0.2 = 0.75 (using P(rain∩late)=0.3×0.5=0.15).",
        "Correct: P(A|B) = P(A∩B)/P(B).",
        "Second draw depends on first — P(R2|R1) ≠ P(R2).",
        "Confused direction; need P(spam∩'free')/P('free').",
        "(5/8)×(4/7) = 20/56 = 5/14.",
        "Compute both from table; numerators differ.",
        "Independence means P(A∩B)=P(A)P(B), so P(A|B)=P(A∩B)/P(B)=P(A).",
        "P(attack|alert) = 45/(45+10) = 45/55 ≈ 0.818.",
        "Estimate P(spam|word) from counts; combine words for classification.",
        "Card draws without replacement, or correlated network failures.",
    ],
    "glossary_builds": {"conditional probability": "8.1 Probability Basics", "given": "8.1 Probability Basics", "joint probability": "8.1 Probability Basics", "independence": "8.1 Probability Basics", "dependence": "8.2 Conditional Probability"},
    "glossary_cs": {
        "conditional probability": "Spam scores and fraud alerts compute P(threat | observed features).",
        "given": "Every if-statement checking context before acting uses a 'given' condition.",
        "joint probability": "P(user clicks AND ad shown) drives joint engagement metrics.",
        "independence": "Assuming feature independence simplifies Naive Bayes classifiers.",
        "dependence": "Correlated failures in distributed systems violate independence assumptions.",
    },
    "cum_marks": 5,
    "cum_questions": [
        "Write P(A|B) in words and as a formula. (1 mark)",
        "P(A∩B)=0.08, P(B)=0.2. Find P(A|B). (1 mark)",
        "Define independence. (1 mark)",
        "Give one dependent pair of events. (1 mark)",
        "P(spam)=0.4, P('winner'|spam)=0.5, P('winner'|ham)=0.01. Which is larger: P('winner'|spam) or P(spam|'winner')? Explain briefly. (1 mark)",
    ],
})
