"""Topic data for Module 11 generator."""
from module_11_helpers import make_topic

TOPICS = [
    make_topic(
        id="11.1", title="Advanced Complexity Theory",
        tags="#maths/complexity #maths/proof #cs/algorithms",
        breadcrumbs=["10.1 Big O Theta and Omega", "10.2 Algorithm Complexity Case Studies",
                     "5.11 Proof by Induction", "5.9 Direct Proof and Counterexample",
                     "10.12 Research Paper Maths Reading"],
        prereq=["10.12 Research Paper Maths Reading", "5.11 Proof by Induction"],
        used_later=["11.2 Randomised Algorithms"],
        next="11.2 Randomised Algorithms",
        plain="Beyond basic P and NP: **reductions** show one problem is at least as hard as another; **NP-complete** problems are the hardest in NP; **co-NP**, **PSPACE**, and the **complexity hierarchy** organise what time and space buy you.",
        everyday="If packing a van optimally is NP-hard, a logistics company may accept a 10% longer route from a fast heuristic rather than wait years for perfection.",
        terms=[
            ("reduction", "A polynomial-time transformation from problem A to B showing A is no harder than B; if B is easy, A is easy; if A is hard, B is hard."),
            ("NP-complete", "A decision problem in NP to which every NP problem reduces in polynomial time — the hardest problems inside NP."),
            ("co-NP", "The class of decision problems whose complements lie in NP; e.g. proving a formula is unsatisfiable."),
            ("PSPACE", "Problems solvable using polynomial space (memory), possibly exponential time; includes many games and quantified logic."),
            ("complexity hierarchy", "The tower of classes (P ⊆ NP ⊆ PSPACE ⊆ EXPTIME, etc.) ordered by provable or conjectured inclusions."),
        ],
        cs_one_liner="Complexity theory explains what efficient computation may or may not achieve.",
        plain_short="Reductions, NP-completeness, and complexity classes beyond P and NP.",
        theme="complexity",
    ),
    make_topic(
        id="11.2", title="Randomised Algorithms",
        tags="#maths/probability #maths/complexity #cs/algorithms",
        breadcrumbs=["11.1 Advanced Complexity Theory", "5.11 Proof by Induction",
                     "8.1 Probability Basics", "10.1 Big O Theta and Omega", "5.9 Direct Proof and Counterexample"],
        prereq=["11.1 Advanced Complexity Theory", "5.11 Proof by Induction"],
        used_later=["11.3 Approximation Algorithms"],
        next="11.3 Approximation Algorithms",
        plain="**Randomised algorithms** flip coins during execution. **Las Vegas** algorithms always return correct answers (variable time); **Monte Carlo** algorithms may err with small probability (fixed time). **Expected runtime** and **amplification** make randomness reliable.",
        everyday="QuickSort picks a random pivot so bad inputs are unlikely — average case fast without sorting the data first.",
        terms=[
            ("randomised algorithm", "An algorithm that uses random choices during execution, often to improve average performance or simplify design."),
            ("Las Vegas algorithm", "A randomised algorithm that always outputs the correct answer but whose running time is a random variable."),
            ("Monte Carlo algorithm", "A randomised algorithm with fixed running time that may produce an incorrect answer with small probability."),
            ("expected runtime", "The average running time over all random choices, weighted by their probabilities."),
            ("amplification", "Repeating a Monte Carlo test many times to drive the error probability down exponentially."),
        ],
        cs_one_liner="Randomisation helps hashing, primality tests, sampling, and distributed systems.",
        plain_short="Las Vegas vs Monte Carlo, expected time, and error amplification.",
        theme="randomised",
    ),
    make_topic(
        id="11.3", title="Approximation Algorithms",
        tags="#maths/algorithms #maths/proof #cs/optimisation",
        breadcrumbs=["11.2 Randomised Algorithms", "5.11 Proof by Induction",
                     "10.2 Algorithm Complexity Case Studies", "6.4 Graphs Basics", "5.9 Direct Proof and Counterexample"],
        prereq=["11.2 Randomised Algorithms", "5.11 Proof by Induction"],
        used_later=["11.4 Advanced Graph Theory"],
        next="11.4 Advanced Graph Theory",
        plain="When exact **optimal solutions** are too expensive, **approximation algorithms** guarantee solutions within a factor of the best. The **approximation ratio** measures quality; **hardness** shows limits; a **PTAS** approaches optimality as runtime grows.",
        everyday="A delivery app may route drivers within 20% of the shortest total distance because finding the true optimum for 500 stops is impractical.",
        terms=[
            ("approximation ratio", "The worst-case factor ρ such that ALG ≤ ρ·OPT (minimisation) or ALG ≥ OPT/ρ (maximisation)."),
            ("greedy algorithm", "A method that repeatedly takes the locally best choice; often fast and sometimes provably good approximations."),
            ("optimal solution", "A solution achieving the best possible objective value for an optimisation instance."),
            ("hardness", "A proof that no efficient algorithm can achieve a given approximation factor unless complexity assumptions fail."),
            ("PTAS", "Polynomial-Time Approximation Scheme: for every ε>0, a (1+ε)-approximation in time polynomial in n (but possibly exponential in 1/ε)."),
        ],
        cs_one_liner="Approximation is essential for scheduling, routing, and optimisation problems.",
        plain_short="Approximation ratios, greedy methods, and hardness of approximation.",
        theme="approximation",
    ),
    make_topic(
        id="11.4", title="Advanced Graph Theory",
        tags="#maths/graphs #maths/algorithms #cs/networks",
        breadcrumbs=["11.3 Approximation Algorithms", "6.4 Graphs Basics",
                     "10.2 Algorithm Complexity Case Studies", "5.11 Proof by Induction", "6.6 Trees and Spanning Trees"],
        prereq=["11.3 Approximation Algorithms"],
        used_later=["11.5 Statistical Learning Theory"],
        next="11.5 Statistical Learning Theory",
        plain="Deep graph structure: **matchings** pair vertices; **flow networks** model capacity; **cuts** separate source from sink; **planar graphs** embed in the plane; **connectivity** measures resilience.",
        everyday="Airline hub planning uses max-flow to estimate how many passengers a network can move before bottlenecks appear.",
        terms=[
            ("matching", "A set of edges with no shared vertices; a perfect matching covers every vertex exactly once."),
            ("flow network", "A directed graph with source, sink, capacities on edges, and a feasible flow respecting capacity and conservation."),
            ("cut", "A partition of vertices into S and V\\S; cut capacity is the sum of capacities from S to V\\S."),
            ("planar graph", "A graph drawable in the plane with no crossing edges; satisfies Euler's formula v - e + f = 2."),
            ("connectivity", "The minimum number of vertices or edges whose removal disconnects the graph; measures network robustness."),
        ],
        cs_one_liner="Advanced graph theory supports networks, compilers, logistics, and verification.",
        plain_short="Matchings, max-flow min-cut, planarity, and connectivity.",
        theme="graphs",
    ),
    make_topic(
        id="11.5", title="Statistical Learning Theory",
        tags="#maths/probability #maths/ml #cs/learning",
        breadcrumbs=["11.4 Advanced Graph Theory", "8.1 Probability Basics",
                     "8.7 Descriptive Statistics", "5.11 Proof by Induction", "10.8 Machine Learning Vectors and Matrices"],
        prereq=["11.4 Advanced Graph Theory", "8.1 Probability Basics"],
        used_later=["11.6 Probabilistic Graphical Models"],
        next="11.6 Probabilistic Graphical Models",
        plain="**Training error** fits past data; **test error** predicts future data. **VC dimension** measures model capacity; **bias-variance** trade-off explains over- and under-fitting; **generalisation bounds** quantify risk.",
        everyday="A model that memorises every exam question fails the real test — learning theory asks when memorisation still generalises.",
        terms=[
            ("training error", "The fraction of misclassified or high-loss training examples — performance on data used to fit the model."),
            ("test error", "Performance on held-out data not used during training — estimates future generalisation."),
            ("VC dimension", "The largest number of points a hypothesis class can shatter — a capacity measure for generalisation."),
            ("bias variance", "Bias is systematic under-fitting; variance is sensitivity to training sample noise — together they decompose expected error."),
            ("generalisation bound", "A proved inequality linking training error, complexity, and test error with high probability."),
        ],
        cs_one_liner="Learning theory explains when ML models may work beyond training data.",
        plain_short="Train vs test error, VC dimension, bias-variance, generalisation bounds.",
        theme="learning_theory",
    ),
    make_topic(
        id="11.6", title="Probabilistic Graphical Models",
        tags="#maths/probability #maths/graphs #cs/ml",
        breadcrumbs=["11.5 Statistical Learning Theory", "8.1 Probability Basics",
                     "8.10 Bayesian Inference", "6.4 Graphs Basics", "5.7 Implication and Equivalence"],
        prereq=["11.5 Statistical Learning Theory"],
        used_later=["11.7 Advanced Optimisation for ML"],
        next="11.7 Advanced Optimisation for ML",
        plain="**Bayesian networks** and **Markov random fields** encode joint distributions as graphs. **Conditional independence** simplifies inference; **factor graphs** unify message passing; **inference** computes marginals or MAP estimates.",
        everyday="Medical diagnosis apps use Bayesian nets: symptoms depend on hidden diseases; knowing one test result may make others irrelevant.",
        terms=[
            ("Bayesian network", "A directed acyclic graph where nodes are random variables and edges encode direct dependencies via conditional distributions."),
            ("Markov random field", "An undirected graphical model where the joint factorises over cliques; encodes symmetric dependencies."),
            ("conditional independence", "X ⊥ Y | Z means knowing Z makes X and Y independent — read off from graph separation."),
            ("factor graph", "A bipartite graph of variables and factors representing a product of potential functions."),
            ("inference", "Computing posterior marginals P(X|evidence) or the most probable assignment (MAP) in a graphical model."),
        ],
        cs_one_liner="PGMs support diagnosis, NLP, robotics, and causal modelling.",
        plain_short="Bayesian nets, MRFs, conditional independence, and inference.",
        theme="pgm",
    ),
    make_topic(
        id="11.7", title="Advanced Optimisation for ML",
        tags="#maths/calculus #maths/ml #cs/optimisation",
        breadcrumbs=["11.6 Probabilistic Graphical Models", "9.9 Gradient Descent and Optimisation",
                     "9.10 Convex Optimisation Basics", "3.2 Function Notation and Mapping", "4.8 Vectors Basics"],
        prereq=["11.6 Probabilistic Graphical Models", "3.2 Function Notation and Mapping"],
        used_later=["11.8 Multivariable Calculus for Deep Learning"],
        next="11.8 Multivariable Calculus for Deep Learning",
        plain="Training neural nets is **optimisation** over a **loss landscape**. **SGD** uses noisy gradients; **momentum** accelerates; **Adam** adapts step sizes; **regularisation** prevents overfitting.",
        everyday="Descent with momentum is like a ball rolling downhill — it keeps moving past flat patches that would stop plain gradient descent.",
        terms=[
            ("SGD", "Stochastic Gradient Descent: update parameters using a random mini-batch gradient instead of the full dataset gradient."),
            ("momentum", "An optimisation technique adding a velocity term so updates accumulate direction and damp oscillations."),
            ("Adam", "Adaptive Moment Estimation: per-parameter learning rates from running averages of gradient and squared gradient."),
            ("regularisation", "A penalty term (e.g. L2 weight decay) added to the loss to discourage complex models and improve generalisation."),
            ("loss landscape", "The graph of loss L(θ) over parameter space θ; saddle points and sharp minima affect trainability."),
        ],
        cs_one_liner="Training deep learning systems is largely an optimisation problem.",
        plain_short="SGD, momentum, Adam, regularisation, and loss landscapes.",
        theme="optimisation",
    ),
    make_topic(
        id="11.8", title="Multivariable Calculus for Deep Learning",
        tags="#maths/calculus #maths/ml #cs/neural-networks",
        breadcrumbs=["11.7 Advanced Optimisation for ML", "9.3 Differentiation Rules",
                     "9.8 Multivariable Functions", "4.8 Vectors Basics", "3.2 Function Notation and Mapping"],
        prereq=["11.7 Advanced Optimisation for ML", "3.2 Function Notation and Mapping", "8.1 Probability Basics"],
        used_later=["11.9 Linear Algebra for Representation Learning"],
        next="11.9 Linear Algebra for Representation Learning",
        plain="Deep learning needs **gradients** of vector-valued functions via the **Jacobian**, curvature via the **Hessian**, and **backpropagation** as the **chain rule** applied layer by layer.",
        everyday="Adjusting thousands of neural weights to reduce error is multivariable calculus — each weight gets a partial derivative telling it which way to move.",
        terms=[
            ("gradient", "The vector of partial derivatives ∇f pointing in the direction of steepest increase of scalar f."),
            ("Jacobian", "The matrix of partial derivatives ∂f_i/∂x_j for a vector function f: R^n → R^m."),
            ("Hessian", "The matrix of second partial derivatives of a scalar function; reveals curvature and saddle structure."),
            ("backpropagation", "Efficient algorithm computing gradients in layered networks by reverse application of the chain rule."),
            ("chain rule", "If y = f(g(x)), then dy/dx = (df/dg)(dg/dx); extends to multivariate compositions for neural layers."),
        ],
        cs_one_liner="Backpropagation is multivariable calculus implemented at scale.",
        plain_short="Gradients, Jacobians, Hessians, chain rule, and backprop.",
        theme="calculus_dl",
    ),
    make_topic(
        id="11.9", title="Linear Algebra for Representation Learning",
        tags="#maths/linear-algebra #maths/ml #cs/embeddings",
        breadcrumbs=["11.8 Multivariable Calculus for Deep Learning", "4.8 Vectors Basics",
                     "4.9 Matrices Basics", "10.8 Machine Learning Vectors and Matrices", "8.1 Probability Basics"],
        prereq=["11.8 Multivariable Calculus for Deep Learning", "4.8 Vectors Basics", "8.1 Probability Basics"],
        used_later=["11.10 Numerical Methods and Stability"],
        next="11.10 Numerical Methods and Stability",
        plain="Data lives in **embedding spaces**. **Projections** and **low-rank approximations** compress information; **singular vectors** from SVD reveal principal directions; **latent factors** capture hidden structure.",
        everyday="Word2vec maps words to vectors so 'king - man + woman ≈ queen' — geometry encodes meaning.",
        terms=[
            ("embedding space", "A vector space where objects (words, users, images) are represented as points whose geometry reflects similarity."),
            ("projection", "Mapping a vector onto a subspace — e.g. PCA projects data onto principal components."),
            ("low-rank approximation", "Replacing a matrix by a rank-k matrix (k small) that minimises reconstruction error — compression and denoising."),
            ("singular vector", "Left or right singular vector from SVD; directions of maximal variance or response in matrix data."),
            ("latent factor", "An unobserved variable represented as a coordinate in a low-dimensional factorisation (e.g. matrix factorisation)."),
        ],
        cs_one_liner="Representation learning turns data into useful vector spaces.",
        plain_short="Embeddings, projections, SVD, low-rank models, latent factors.",
        theme="linalg_rep",
    ),
    make_topic(
        id="11.10", title="Numerical Methods and Stability",
        tags="#maths/numerics #maths/calculus #cs/simulation",
        breadcrumbs=["11.9 Linear Algebra for Representation Learning", "10.4 Floating Point and Rounding Error",
                     "9.1 Limits and Continuity", "4.9 Matrices Basics", "1.13 Estimation and Error Checking"],
        prereq=["11.9 Linear Algebra for Representation Learning"],
        used_later=["11.11 Category Theory for CS Intro"],
        next="11.11 Category Theory for CS Intro",
        plain="Computers approximate continuously. **Iteration** solves equations; **convergence** checks limits; **stability** asks whether errors stay bounded; **conditioning** measures sensitivity; **discretisation** replaces continua with grids.",
        everyday="Simulating weather on a grid replaces continuous atmosphere equations — tiny rounding errors can grow if the method is unstable.",
        terms=[
            ("iteration", "Repeated application of an update rule x_{k+1} = g(x_k) until a fixed point or convergence criterion is met."),
            ("convergence", "A sequence or iterative method approaching a limit as step count increases."),
            ("stability", "Property that small input or rounding errors do not grow unboundedly through the algorithm."),
            ("conditioning", "How much relative output error amplifies relative input error — ill-conditioned problems need extra care."),
            ("discretisation", "Replacing continuous variables (time, space) with finite steps or mesh points for numerical solution."),
        ],
        cs_one_liner="Scientific computing and ML depend on stable numerical approximations.",
        plain_short="Iteration, convergence, stability, conditioning, discretisation.",
        theme="numerics",
    ),
    make_topic(
        id="11.11", title="Category Theory for CS Intro",
        tags="#maths/category #maths/proof #cs/plt",
        breadcrumbs=["11.10 Numerical Methods and Stability", "5.1 Set Theory Basics",
                     "3.2 Function Notation and Mapping", "5.7 Implication and Equivalence", "10.11 Type Theory and Program Logic Intro"],
        prereq=["11.10 Numerical Methods and Stability"],
        used_later=["11.12 Lambda Calculus and Formal Semantics"],
        next="11.12 Lambda Calculus and Formal Semantics",
        plain="A **category** has **objects** and **morphisms** (arrows) with composition and identity. **Functors** map categories; **monads** structure computations with effects — familiar from Haskell and functional design patterns.",
        everyday="Functor laws say mapping a list twice is the same as mapping once with composed functions — a reusable abstraction guarantee.",
        terms=[
            ("category", "A collection of objects and morphisms between them, with associative composition and identity arrows."),
            ("object", "A node in a category — may represent a type, set, or semantic domain rather than a physical thing."),
            ("morphism", "An arrow f: A → B in a category; generalises functions, homomorphisms, and structure-preserving maps."),
            ("functor", "A mapping between categories that preserves composition and identities — models type constructors and transformations."),
            ("monad", "A functor T with unit η and join μ satisfying laws; encapsulates sequential computation with effects (state, IO, failure)."),
        ],
        cs_one_liner="Functional programming and semantics borrow ideas from category theory.",
        plain_short="Categories, functors, monads, and composition laws.",
        theme="category",
    ),
    make_topic(
        id="11.12", title="Lambda Calculus and Formal Semantics",
        tags="#maths/logic #maths/plt #cs/semantics",
        breadcrumbs=["11.11 Category Theory for CS Intro", "3.2 Function Notation and Mapping",
                     "5.5 Propositional Logic", "10.11 Type Theory and Program Logic Intro", "5.11 Proof by Induction"],
        prereq=["11.11 Category Theory for CS Intro", "3.2 Function Notation and Mapping"],
        used_later=["11.13 Finite Fields and Polynomial Arithmetic"],
        next="11.13 Finite Fields and Polynomial Arithmetic",
        plain="**Lambda expressions** define anonymous functions; **variable binding** and substitution need care; **beta reduction** applies functions; **normal form** is fully reduced; **semantics** assigns mathematical meaning to programs.",
        everyday="`(λx.x+1) 3` means 'the function that adds 1, applied to 3' — the blueprint of functional programming.",
        terms=[
            ("lambda expression", "An anonymous function written λx.M where x is bound in body M; core of functional languages."),
            ("variable binding", "Associating a variable name with a value or parameter scope; free vs bound variables must be tracked."),
            ("beta reduction", "Applying a lambda: (λx.M) N reduces to M[N/x] — substitute N for x in M."),
            ("normal form", "An expression that cannot reduce further; may not exist unless evaluation terminates."),
            ("semantics", "A mathematical account of what programs mean — operational (steps) or denotational (values)."),
        ],
        cs_one_liner="Programming language theory uses lambda calculus as a core model.",
        plain_short="Lambda terms, beta reduction, binding, normal forms, semantics.",
        theme="lambda",
    ),
    make_topic(
        id="11.13", title="Finite Fields and Polynomial Arithmetic",
        tags="#maths/algebra #maths/crypto #cs/coding",
        breadcrumbs=["11.12 Lambda Calculus and Formal Semantics", "2.9 Indices and Powers",
                     "1.10 Factors Multiples and Primes", "10.3 Binary Hexadecimal and Number Bases", "5.9 Direct Proof and Counterexample"],
        prereq=["11.12 Lambda Calculus and Formal Semantics"],
        used_later=["11.14 Elliptic Curve Cryptography"],
        next="11.14 Elliptic Curve Cryptography",
        plain="A **finite field** has finitely many **field elements** with addition and multiplication mod a prime or **polynomial modulo** an **irreducible polynomial**. Every nonzero element has a **multiplicative inverse**.",
        everyday="AES mixes bytes using GF(2^8) arithmetic — same addition rules as XOR, but with structured multiplication.",
        terms=[
            ("finite field", "A field with finitely many elements; size is p^n for prime p — e.g. Z_p or GF(2^m)."),
            ("polynomial modulo", "Polynomial arithmetic where coefficients are in a field and we identify polynomials differing by multiples of a fixed mod polynomial."),
            ("irreducible polynomial", "A polynomial that cannot factor nontrivially over the field — plays the role of prime for extension fields."),
            ("field element", "A member of a field; in GF(2^m), often represented as a bit vector or polynomial."),
            ("multiplicative inverse", "For a ≠ 0, the element a^{-1} with a·a^{-1} = 1; exists uniquely in a field."),
        ],
        cs_one_liner="Finite fields power error correction and cryptographic protocols.",
        plain_short="GF(p^n), polynomial mod arithmetic, inverses, irreducibles.",
        theme="finite_fields",
    ),
    make_topic(
        id="11.14", title="Elliptic Curve Cryptography",
        tags="#maths/crypto #maths/algebra #cs/security",
        breadcrumbs=["11.13 Finite Fields and Polynomial Arithmetic", "10.6 Cryptography RSA and Diffie Hellman",
                     "1.10 Factors Multiples and Primes", "5.11 Proof by Induction", "10.5 Hashing and Checksums"],
        prereq=["11.13 Finite Fields and Polynomial Arithmetic"],
        used_later=["11.15 Lattice-Based Cryptography"],
        next="11.15 Lattice-Based Cryptography",
        plain="Points on an **elliptic curve** form a group under a geometric **group law**. **Scalar multiplication** kP is fast one way; **ECDH** key exchange and **ECDSA** signatures use smaller keys than RSA.",
        everyday="Your phone's secure connection may use curve25519 — elliptic curves give strong security with shorter keys than RSA.",
        terms=[
            ("elliptic curve", "A smooth cubic curve y² = x³ + ax + b over a field, plus a point at infinity forming a group."),
            ("group law", "Rule for adding two curve points P + Q to get a third point R on the curve; associative with identity O."),
            ("scalar multiplication", "Computing kP = P + P + ... + P (k times) efficiently via double-and-add; hard to invert (ECDLP)."),
            ("ECDH", "Elliptic Curve Diffie-Hellman: shared secret from a·(bG) = b·(aG) without transmitting private scalars."),
            ("ECDSA", "Elliptic Curve Digital Signature Algorithm: sign with private scalar; verify with public point and hash."),
        ],
        cs_one_liner="ECC secures many modern systems with smaller keys than RSA.",
        plain_short="Curve groups, scalar mult, ECDH, ECDSA.",
        theme="ecc",
    ),
    make_topic(
        id="11.15", title="Lattice-Based Cryptography",
        tags="#maths/crypto #maths/lattices #cs/security",
        breadcrumbs=["11.14 Elliptic Curve Cryptography", "4.8 Vectors Basics",
                     "4.9 Matrices Basics", "10.6 Cryptography RSA and Diffie Hellman", "5.10 Proof by Contradiction and Contrapositive"],
        prereq=["11.14 Elliptic Curve Cryptography"],
        used_later=["11.16 Quantum Computing Maths Intro"],
        next="11.16 Quantum Computing Maths Intro",
        plain="A **lattice** is all integer combinations of **basis** vectors. **SVP** (shortest vector) and **LWE** (Learning With Errors) problems resist quantum attacks; leading **post-quantum** schemes use lattice hardness.",
        everyday="Post-quantum TLS candidates hide messages in noisy linear equations — easy with the secret, hard without.",
        terms=[
            ("lattice", "The set {Σ z_i b_i : z_i ∈ Z} of integer linear combinations of basis vectors b_i in R^n."),
            ("basis", "A linearly independent set of vectors that generate the lattice; many bases describe the same lattice."),
            ("shortest vector problem", "Find a nonzero lattice vector of minimum Euclidean length — believed hard in high dimensions."),
            ("Learning With Errors", "Distinguish (A, As + e mod q) from uniform, where s is secret and e is small noise — LWE hardness assumption."),
            ("post-quantum", "Cryptography designed to remain secure if large-scale quantum computers break RSA and ECC."),
        ],
        cs_one_liner="Lattice cryptography is a leading path for post-quantum systems.",
        plain_short="Lattices, SVP, LWE, post-quantum KEMs.",
        theme="lattice",
    ),
    make_topic(
        id="11.16", title="Quantum Computing Maths Intro",
        tags="#maths/quantum #maths/linear-algebra #cs/quantum",
        breadcrumbs=["11.15 Lattice-Based Cryptography", "4.9 Matrices Basics",
                     "4.8 Vectors Basics", "8.1 Probability Basics", "10.6 Cryptography RSA and Diffie Hellman"],
        prereq=["11.15 Lattice-Based Cryptography"],
        used_later=["11.17 Information Theory for ML and Compression"],
        next="11.17 Information Theory for ML and Compression",
        plain="A **qubit** is |ψ⟩ = α|0⟩ + β|1⟩ in **superposition**. Gates are **unitary matrices**; **measurement** collapses to classical outcomes; multi-qubit states use the **tensor product**.",
        everyday="Grover's search gives quadratic speedup for unstructured search — not magic, but different rules for probability amplitudes.",
        terms=[
            ("qubit", "A two-level quantum system with state |ψ⟩ = α|0⟩ + β|1⟩ where |α|² + |β|² = 1."),
            ("superposition", "A linear combination of basis states existing simultaneously until measured."),
            ("unitary matrix", "A matrix U with U†U = I; quantum gates preserve norm and are reversible."),
            ("measurement", "Process yielding classical outcome k with probability |⟨k|ψ⟩|² and collapsing the state to |k⟩."),
            ("tensor product", "Combining spaces: |ψ⟩⊗|φ⟩ lives in the product Hilbert space of multiple qubits."),
        ],
        cs_one_liner="Quantum computing changes assumptions in algorithms and cryptography.",
        plain_short="Qubits, unitaries, measurement, tensor products.",
        theme="quantum",
    ),
    make_topic(
        id="11.17", title="Information Theory for ML and Compression",
        tags="#maths/information #maths/ml #cs/compression",
        breadcrumbs=["11.16 Quantum Computing Maths Intro", "8.11 Information Theory",
                     "8.1 Probability Basics", "10.9 Neural Network Maths", "5.11 Proof by Induction"],
        prereq=["11.16 Quantum Computing Maths Intro", "8.1 Probability Basics"],
        used_later=["11.18 Research Methods and Mathematical Writing"],
        next="11.18 Research Methods and Mathematical Writing",
        plain="**Cross-entropy** trains classifiers; **KL divergence** measures distribution mismatch; **mutual information** quantifies shared information; **coding theorems** link entropy to **compression bounds**.",
        everyday="JPEG and language models both trade bits for fidelity — information theory sets the limit on how much you can compress.",
        terms=[
            ("KL divergence", "D_KL(P||Q) = Σ P(x) log(P(x)/Q(x)) — nonnegative; zero iff P = Q; not symmetric."),
            ("cross entropy", "H(P,Q) = -Σ P(x) log Q(x); common classification loss when P is true labels and Q is model."),
            ("mutual information", "I(X;Y) = H(X) - H(X|Y) — reduction in uncertainty about X from knowing Y."),
            ("coding theorem", "Shannon's source coding: average code length ≥ H(X); achievable with optimal codes."),
            ("compression bound", "Fundamental limit on lossless compression rate given by entropy; lossy schemes trade rate for distortion."),
        ],
        cs_one_liner="Modern ML losses and compression theory share information-theoretic roots.",
        plain_short="Cross-entropy, KL, mutual information, coding limits.",
        theme="info_theory",
    ),
    make_topic(
        id="11.18", title="Research Methods and Mathematical Writing",
        tags="#maths/writing #maths/proof #cs/research",
        breadcrumbs=["11.17 Information Theory for ML and Compression", "10.12 Research Paper Maths Reading",
                     "5.9 Direct Proof and Counterexample", "5.11 Proof by Induction", "5.7 Implication and Equivalence"],
        prereq=["11.17 Information Theory for ML and Compression"],
        used_later=["Master's-level review and research reading"],
        next="Master's-level review and research reading",
        plain="Research maths needs precise **definitions**, consistent **notation**, clear **claims**, structured **proof outlines**, and a **literature review** that situates your contribution.",
        everyday="A thesis reviewer rejects vague theorems — 'clearly converges' is not a proof; state assumptions and cite prior work.",
        terms=[
            ("definition", "A precise statement introducing a new mathematical object or property, with all conditions explicit."),
            ("notation", "A consistent system of symbols; must be declared before use and not overloaded without warning."),
            ("claim", "A theorem, lemma, proposition, or conjecture stated formally with hypotheses and conclusion separated."),
            ("proof outline", "A high-level proof strategy listing key steps before filling algebraic detail — guides reader and author."),
            ("literature review", "Structured summary of prior work showing gaps your research addresses; cites primary sources."),
        ],
        cs_one_liner="Master's projects require precise technical communication.",
        plain_short="Definitions, notation, claims, proofs, literature reviews.",
        theme="research_writing",
    ),
]
