# Part 2: Topics 10.2–10.12 — appended to TOPICS list

TOPICS.append({
    "id": "10.2", "title": "Algorithm Complexity Case Studies",
    "tags": "#maths/discrete #cs/complexity #cs/algorithms",
    "prereq": ["10.1 Big O Theta and Omega", "5.11 Proof by Induction", "6.2 Recurrence Relations"],
    "used_later": ["10.3 Binary Hexadecimal and Number Bases", "11.3 Approximation Algorithms"],
    "next": "10.3 Binary Hexadecimal and Number Bases",
    "plain": "This topic applies [[Big O]] notation to **real algorithms**: counting [[loop count]]s, analysing [[recursive cost]], and separating [[best case]], [[average case]], and [[worst case]]. You trace code like a compiler, build recurrence relations from [[6.2 Recurrence Relations]], and verify claims with [[5.11 Proof by Induction]].",
    "everyday": "Finding a name in an unsorted phone book means checking every page (worst case: everyone). In a sorted book you can jump to the middle (much faster). Same task — different algorithm — different case analysis.",
    "terms": [
        ("best case", "minimum operations over all inputs of size n."),
        ("average case", "expected operations averaged over typical inputs of size n."),
        ("worst case", "maximum operations over all inputs of size n."),
        ("loop count", "number of times a loop body executes for input size n."),
        ("recursive cost", "total work of a recursive function expressed as T(n) with base cases."),
    ],
    "concepts": [
        concept("Counting Loop Operations", ["Nested loops multiply counts.", "", "```python", "for i in range(n):", "    for j in range(n):", "        print(i, j)", "```", "", "Outer n × inner n = **n²** iterations.", "", "From [[10.1 Big O Theta and Omega]], drop constants → **O(n²)**."], "tip", "Multiply nested loops", ["Three nested loops over n → n³ unless inner range depends on outer."], "Count prints in double loop over n.", ["Outer n.", "Inner n each.", "Total n²."], "**n²** prints, **O(n²)**."),
        concept("Best, Average, Worst Case", ["**Worst case**: adversarial input maximises work.", "**Best case**: easiest input minimises work.", "**Average case**: mean over input distribution.", "", "Linear search:", "- Best: target at index 0 → **O(1)**", "- Worst: target last or absent → **O(n)**", "- Average: target random → **O(n)**"], "important", "State which case", ["Documentation usually quotes worst unless 'average' is specified."], "QuickSort: best vs worst?", ["Best: balanced pivots → O(n log n).", "Worst: bad pivots every time → O(n²).", "Average often O(n log n)."], "Worst **O(n²)**, best **O(n log n)**."),
        concept("Recurrence for Merge Sort", ["Merge sort splits list in half, sorts halves, merges.", "", "```text", "T(n) = 2T(n/2) + O(n)", "```", "", "From [[6.2 Recurrence Relations]] and [[5.11 Proof by Induction]], this solves to **T(n) = Θ(n log n)**."], "example", "Master Theorem preview", ["Divide into a=2 subproblems, size n/2, merge cost O(n) → Θ(n log n)."], "Write recurrence for binary search.", ["Halve problem: T(n) = T(n/2) + O(1).", "Base T(1) = O(1).", "Depth log n."], "**T(n) = T(n/2) + O(1) = O(log n)**."),
        concept("Case Study — Bubble Sort", ["Compare adjacent pairs, swap if wrong order.", "", "Pass i compares about n-i pairs.", "Total comparisons ≈ n(n-1)/2.", "", "**Worst/average: Θ(n²)**. **Best** (already sorted with early exit): **O(n)**."], "warning", "Best ≠ typical", ["Already-sorted best case misleads if data is usually random."], "Why bubble sort is Θ(n²) worst?", ["Double loop over positions.", "~n²/2 comparisons.", "Dominant n²."], "**Θ(n²)** worst case."),
        concept("Case Study — BFS on Graph", ["BFS visits each vertex and edge once.", "V vertices, E edges.", "", "**O(V + E)** using adjacency list.", "", "Links [[6.4 Graph Theory Basics]] to [[10.10 Graphs in Networks and AI Search]]."], "example", "Social network", ["Users = V, friendships = E. BFS finds degrees of separation in O(V+E)."], "Graph with 1000 nodes, 5000 edges — BFS cost?", ["Visit each node once.", "Scan each edge once.", "O(1000 + 5000)."], "**O(V + E) = O(6000)**."),
        concept("Induction Check on Loop Sum", ["Prove 1+2+...+n = n(n+1)/2 from [[5.11 Proof by Induction]].", "That formula counts total inner iterations when inner loop runs i times.", "", "Connects counting to proof."], "important", "Count via formula", ["Triangular loop `for i: for j in range(i)` → Θ(n²)."], "Inner j runs 0..i-1. Total iterations?", ["Sum 1+2+...+n.", "n(n+1)/2.", "Θ(n²)."], "**n(n+1)/2 = Θ(n²)**."),
    ],
    "why": "Case studies work because every algorithm decomposes into loops, recursion, and data-structure operations whose costs add and multiply. Recurrences from [[6.2 Recurrence Relations]] formalise recursive costs; induction from [[5.11 Proof by Induction]] proves closed forms. Big-O from [[10.1 Big O Theta and Omega]] summarises the result.",
    "mistakes": ["Reporting best case as the algorithm's complexity.", "Forgetting hidden loops in library calls.", "Miscounting when inner loop bound depends on outer.", "Ignoring recursion depth.", "Adding O(n) and O(n²) and getting O(n).", "Confusing comparisons with swaps."],
    "failure": "If inner loop runs n times for each of n outer iterations, it is Θ(n²) even if the body looks 'small'.",
    "cs_intro": "Complexity case studies appear in:",
    "cs_body": ["- Choosing sort for nearly-sorted logs", "- Analysing API pagination loops", "- Profiling recursive JSON parsers", "- Interview whiteboard problems", "", "```python", "# O(n) - single pass", "def max_value(arr):", "    m = arr[0]", "    for x in arr:", "        if x > m: m = x", "    return m", "```"],
    "checkpoint": ["What is worst case?", "Count nested n loops.", "Merge sort recurrence?", "Bubble sort worst case?", "BFS complexity?", "Why average ≠ worst?", "Role of induction?", "Linear search cases?", "When is best case O(n) for sort?", "Link to 6.2?"],
    "mini_quiz": ["Classify triple nested n loop.", "QuickSort worst case?", "T(n)=2T(n/2)+n solution?", "BFS on tree with n nodes?", "Spot: 'single loop so O(1)'.", "Average linear search?", "Recursive factorial T(n)?", "Compare merge vs bubble.", "Count i=0..n-1, j=0..i.", "Why case analysis matters in CS?"],
    "pass_gate": ["count loop iterations for given code", "write simple recurrence", "state best/worst/average for standard algorithms", "connect to graph traversal cost"],
    "worked": [
        {"title": "Nested Loops", "q": "Count work in double loop n×n.", "steps": ["Outer n.", "Inner n.", "Product n²."], "answer": "Θ(n²)"},
        {"title": "Linear Search Cases", "q": "Best, worst, average for unsorted array.", "steps": ["Best: first element.", "Worst: last/absent.", "Average: n/2 comparisons → O(n)."], "answer": "O(1), O(n), O(n)"},
        {"title": "Recurrence", "q": "T(n)=T(n-1)+1, T(1)=1.", "steps": ["Unroll: n steps.", "Linear."], "answer": "T(n)=O(n)"},
        {"title": "Spot Mistake", "q": "Student: 'QuickSort always O(n log n)'.", "steps": ["Worst case O(n²) with bad pivots.", "Average often n log n."], "answer": "Wrong — worst is O(n²)"},
        {"title": "BFS", "q": "Graph V=50, E=200.", "steps": ["O(V+E).", "250 operations order."], "answer": "O(250)=O(V+E)"},
        {"title": "Triangular Loop", "q": "for i in range(n): for j in range(i): pass", "steps": ["Sum 0+1+...+(n-1).", "n(n-1)/2.", "Θ(n²)."], "answer": "Θ(n²)"},
    ],
    "self_check": ["best vs worst vs average", "how to count nested loops", "simple recurrence unrolling", "BFS O(V+E) reasoning"],
    "practice_sections": [
        ["Define best/average/worst case.", "Define loop count.", "Define recursive cost.", "When use worst case?", "Link to Big-O."],
        ["Count n×n loop.", "Count halving loop.", "T(n)=T(n/2)+1.", "Merge sort case.", "Insertion sort worst.", "BFS edges+vertices."],
        ["'Best O(1) so O(1) algorithm'.", "Missed inner loop.", "Confused O(n)+O(n) with O(n²)?"],
        ["Rank bubble, merge, binary search.", "Recurrence for linear search?", "n=1000, n² vs n log n?", "Prove loop sum n(n+1)/2."],
        ["Why Python sort is Timsort?", "Database full scan vs index?", "When O(n²) fails at scale?", "Profile a nested loop app.", "Interview: reverse a linked list cost?"],
    ],
    "practice_answers": [
        ["minimum ops", "expected ops", "T(n) recurrence", "body executions", "maximum ops"],
        ["n²", "log n", "O(log n)", "O(n log n)", "O(n²)", "O(V+E)"],
        ["Must cite worst unless asked", "Multiply loop bounds", "O(n)+O(n)=O(n) not O(n²) unless nested"],
        ["merge n log n < bubble n²", "T(n)=T(n-1)+O(1)", "n log n ≈ 10000, n²=1M", "induction or formula"],
        ["Hybrid O(n log n) worst", "Index O(log n) lookup", "n>10⁴ often", "Hot loop in profiler", "O(n) single pass"],
    ],
    "mastery_b": ["Count triple loop n.", "Worst insertion sort?", "T(n)=2T(n/2)+n?", "BFS tree n nodes?", "Linear search worst?", "Halving n: iterations?"],
    "mastery_c": ["Best case as only analysis.", "O(n) claimed for n² loop."],
    "mastery_d": ["Write recurrence binary search.", "Compare merge vs quick worst.", "Triangular loop count formula.", "Why BFS not O(V²)?"],
    "mastery_e": ["Pick sort for 1M records.", "API design and loop counts.", "Link induction to loop proof."],
    "mastery_answers": [
        "min operations", "expected over inputs", "max operations", "loop body runs", "T(n) recursive cost",
        "n³", "O(n²)", "O(n log n)", "O(n)", "O(n)", "log n",
        "Worst required for guarantees", "n×n iterations",
        "T(n/2)+O(1)", "Merge Θ(n log n) vs quick O(n²) worst", "n(n-1)/2", "Each edge checked once with adj list",
        "Merge sort stable n log n", "Avoid N+1 queries", "Induction proves sum formula",
    ],
    "glossary_builds": {"best case": "10.1 Big O Theta and Omega", "average case": "8.1 Probability Basics", "worst case": "10.1 Big O Theta and Omega", "loop count": "1.1 Counting and Number Sense", "recursive cost": "6.2 Recurrence Relations"},
    "glossary_cs": {"best case": "Optimistic profiling when input is structured.", "average case": "Expected runtime under random input models.", "worst case": "SLA and security analysis use worst-case bounds.", "loop count": "Detecting N+1 query patterns in ORMs.", "recursive cost": "Analysing divide-and-conquer and tree recursion."},
    "cs_one_liner": "Sorting, searching, and graph traversal all need complexity analysis.",
    "plain_short": "Analyse real algorithms using counts and growth.",
    "cum_questions": ["State worst-case QuickSort and merge sort.", "Count iterations: for i: for j in range(n)."],
})

TOPICS.append({
    "id": "10.3", "title": "Binary Hexadecimal and Number Bases",
    "tags": "#maths/number #cs/representation #cs/systems",
    "prereq": ["10.2 Algorithm Complexity Case Studies", "1.2 Place Value and Number Lines", "2.9 Indices and Powers"],
    "used_later": ["10.4 Floating Point and Rounding Error"],
    "next": "10.4 Floating Point and Rounding Error",
    "plain": "Computers store numbers in **[[binary]]** (base 2). **[[hexadecimal]]** (base 16) compresses binary for humans. A **[[bit]]** is one binary digit; a **[[byte]]** is 8 bits. **[[base conversion]]** uses place value from [[1.2 Place Value and Number Lines]] and powers from [[2.9 Indices and Powers]].",
    "everyday": "Hex colour `#FF5733` is six hex digits — each pair is one byte of red, green, blue.",
    "terms": [
        ("binary", "base-2 system using digits 0 and 1 only."),
        ("hexadecimal", "base-16 system using digits 0–9 and A–F."),
        ("bit", "one binary digit, 0 or 1."),
        ("byte", "group of 8 bits; can represent 256 values (0–255)."),
        ("base conversion", "rewriting a number in another radix using place value."),
    ],
    "concepts": [
        concept("Place Value in Any Base", ["In base b, digit d at position i contributes **d × b^i**.", "", "Decimal 352 = 3×10² + 5×10¹ + 2×10⁰.", "Binary 101 = 1×2² + 0×2¹ + 1×2⁰ = 5.", "", "From [[1.2 Place Value and Number Lines]]."], "tip", "Powers of the base", ["Rightmost digit is b⁰ = 1."], "Convert 1101₂ to decimal.", ["1×8 + 1×4 + 0×2 + 1×1.", "8+4+1=13."], "**13**."),
        concept("Binary Addition", ["Same carry rules as decimal but carry when sum ≥ 2.", "", "```text", "  1 0 1", "+ 0 1 1", "-------", " 1 0 0 0", "```"], "warning", "Carry at 2", ["1+1=10 in binary (0 carry 1)."], "101 + 011?", ["1+1=0 carry1.", "0+1+1=0 carry1.", "1+0+1=0 carry1.", "Result 1000."], "**1000₂**."),
        concept("Hex as Binary Shorthand", ["One hex digit = 4 bits (one **nibble**).", "", "```text", "A = 1010", "F = 1111", "```", "", "FF₁₆ = 11111111₂ = 255."], "example", "Memory dumps", ["Debuggers show addresses in hex because it's compact."], "Convert 2A₁₆ to binary.", ["2 → 0010.", "A → 1010.", "Concatenate."], "**00101010₂**."),
        concept("Decimal to Binary", ["Repeated division by 2; remainders read bottom-up.", "", "13 ÷ 2 → 6 r1", "6 ÷ 2 → 3 r0", "3 ÷ 2 → 1 r1", "1 ÷ 2 → 0 r1", "→ 1101"], "important", "Division method", ["Works for any base — divide by b."], "Convert 19 to binary.", ["19→9r1", "9→4r1", "4→2r0", "2→1r0", "1→0r1."], "**10011₂**."),
        concept("Bytes and Ranges", ["8 bits → 2⁸ = 256 values.", "Unsigned byte: 0–255.", "Signed uses two's complement (preview for [[10.4 Floating Point and Rounding Error]])."], "example", "ASCII", ["Letter 'A' is byte 65 = 0x41."], "How many values in 1 byte?", ["2⁸.", "256."], "**256** distinct values."),
        concept("CS Case Study — IPv4", ["IPv4 address: 4 bytes, often written dotted decimal.", "192.168.0.1 = four bytes.", "Each byte 0–255 = two hex digits."], "example", "Network config", ["Subnet masks use bitwise ops on binary representation."], "Last byte of 192.168.1.255 in hex?", ["255 = FF."], "**0xFF** per byte 255."),
    ],
    "why": "Base conversion preserves numeric value while changing notation — same principle as [[2.6 Rearranging Formulae]]: equivalent forms. Place value from [[1.2 Place Value and Number Lines]] and indices from [[2.9 Indices and Powers]] justify every digit position.",
    "mistakes": ["Reading binary right-to-left for place value wrong.", "Confusing hex digit F with decimal 15 in wrong column.", "Forgetting leading zeros in grouping by 4.", "Off-by-one byte boundaries.", "Adding hex without converting."],
    "failure": "If hex→binary gives wrong length, check each hex digit expands to exactly 4 bits.",
    "cs_intro": "Binary and hex appear in:",
    "cs_body": ["- RAM and register dumps", "- File hex editors", "- Colour codes CSS", "- Bit flags and permissions", "- Machine instruction encoding", "", "```python", "bin(13)   # '0b1101'", "hex(255)  # '0xff'", "int('1011', 2)  # 11", "```"],
    "checkpoint": ["What is a bit?", "How many bits in a byte?", "Convert 1010₂.", "FF hex to decimal?", "Why hex for binary?", "Place value base 2?", "Link to 1.2?", "IPv4 bytes?", "Carry rule binary?", "nibble size?"],
    "mini_quiz": ["101 + 10 binary.", "37 decimal to binary.", "DE hex to decimal.", "How many hex digits for 32 bits?", "Byte range unsigned?", "11001100 to hex.", "2⁴?", "Why 8 bits?", "Permission bit mask 4?", "CS use of hex colours?"],
    "pass_gate": ["convert between decimal, binary, hex", "add small binary numbers", "explain byte and bit", "read memory-style hex dumps"],
    "worked": [
        {"title": "Binary to Decimal", "q": "10110₂", "steps": ["16+4+2=22."], "answer": "22"},
        {"title": "Decimal to Binary", "q": "22", "steps": ["Division chain.", "10110."], "answer": "10110₂"},
        {"title": "Hex to Binary", "q": "B3₁₆", "steps": ["B=1011", "3=0011"], "answer": "10110011₂"},
        {"title": "Spot Mistake", "q": "Student: F = 16 decimal in one hex digit.", "steps": ["F is value 15.", "Base-16 digit max 15."], "answer": "F = 15, not 16"},
        {"title": "Binary Add", "q": "111 + 101", "steps": ["1100."], "answer": "1100₂"},
        {"title": "CS Colour", "q": "Byte values 255,87,51 as hex colour?", "steps": ["FF5733."], "answer": "#FF5733"},
    ],
    "self_check": ["place value in base 2", "hex as 4-bit groups", "byte = 8 bits", "division conversion method"],
    "practice_sections": [
        ["Define binary, hex, bit, byte, base conversion."],
        ["10101₂ to decimal.", "15 to binary.", "A0 hex to decimal.", "11110000 to hex.", "1011+1011.", "How many bytes in 32 bits?"],
        ["F treated as 16.", "Wrong bit order.", "7 bits called byte."],
        ["Rank 0xFF, 255, 11111111₂.", "Convert 256 — one byte?", "IPv4 total bits?"],
        ["Why git objects use sha hex?", "File permission 755 binary?", "Unicode code point U+0041?", "Machine word 64-bit hex digits?", "Debug memory address?"],
    ],
    "practice_answers": [
        ["base-2", "base-16", "0/1 digit", "8 bits", "change radix"],
        ["21", "1111", "160", "F0", "10110", "4"],
        ["F=15", "MSB left", "8 bits required"],
        ["all equal 255", "256 needs 9 bits", "32 bits"],
        ["compact fingerprint", "rwx bits", "65 = 'A'", "16 hex digits", "0x7fff... format"],
    ],
    "mastery_b": ["110010₂ decimal.", "100 decimal binary.", "1F hex decimal.", "Bytes in 128 bits?", "101+1 binary.", "CA hex to binary."],
    "mastery_c": ["Hex add without binary.", "3-bit byte."],
    "mastery_d": ["Explain nibble.", "Why hex for dumps?", "Max unsigned byte?", "Convert 0x100 — fits byte?"],
    "mastery_e": ["CSS colour from RGB.", "Why powers of 2 in CS?", "Link place value 1.2."],
    "mastery_answers": [
        "base-2", "base-16", "single 0/1", "8 bits", "change representation",
        "50", "1100100", "31", "16", "110", "11001010",
        "Convert each digit", "Must be 8 bits",
        "4 bits", "compact", "255", "256 needs 9 bits — overflow",
        "#RRGGBB", "Memory alignment", "digit position × power",
    ],
    "glossary_builds": {"binary": "1.2 Place Value and Number Lines", "hexadecimal": "binary", "bit": "binary", "byte": "bit", "base conversion": "2.9 Indices and Powers"},
    "glossary_cs": {"binary": "All data in RAM is bits.", "hexadecimal": "Compact display in debuggers.", "bit": "Boolean flags and masks.", "byte": "char, UTF-8 code units, network octets.", "base conversion": "Parsing binary protocols and IP addresses."},
    "cs_one_liner": "Computer memory and machine instructions are built from binary.",
    "plain_short": "Represent numbers in bases used by computers.",
    "cum_questions": ["Convert 110101₂ to decimal and hex.", "How many values in one byte?"],
})

# Import topics 10.4–10.12
exec(open("/home/Marau/Marau/University/Maths for CS/scripts/module_10_topics_part3.py").read())
